### ISSUE TITLE
Dataset's mean and std

### ISSUE THREAD

**Issue by xiaohoua** [mlfoundations/open_clip#1007]
I'm doing some experiments on the knowledge distillation clip. But it didn't work well, and I suspect it was the transform of the data set. Could you tell me the parameter Settings of some data sets when openclip did the zero sample experiment? For example, the mean and std I calculated on the SUN397 dataset,  are:
SUN_DEFAULT_MEAN = (0.4758, 0.4603, 0.4248)
SUN_DEFAULT_STD = (0.2358, 0.2343, 0.2469)
But I don't know if that's true. 
Should I use:
OPENAI_DATASET_MEAN = (0.48145466, 0.4578275, 0.40821073)
OPENAI_DATASET_STD = (0.26862954, 0.26130258, 0.27577711) ?
Can you give me some suggestions? I am looking forward to your reply

**Comment by rwightman** [comment]
@xiaohoua generally, you should use the pretrainining mean/std for downstream tasks... for most (but not all) of the models with weights here that is the  mean/std used by openai, a few have the [-1, 1] normalization (mean=std=0.5).
