### ISSUE TITLE
Slow Training Speed

### ISSUE THREAD

**Issue by Crane-YU** [mlfoundations/open_clip#110]
Hi guys,
I'm using the openai-RN50 pretrained model and wanna finetune the weights on my own dataset (my training sample number is around 0.2 million). I'm wandering how long it should take to train the model on 4 GPUs with batch_size=256? My current training time is quite slow, around 1h for 1 epoch.

**Comment by mitchellnw** [comment]
What batch size are you using and what is your GPU utilization?

**Comment by Crane-YU** [comment]
Hi, my problem has been sovled by reforming the data loading process
