### ISSUE TITLE
data cleaning for laion 

### ISSUE THREAD

**Issue by Deadsec69** [mlfoundations/open_clip#112]
I was trying with laion400m dataset.The titles there are dirty not clean.Just wanna know what preprocessing is used for cleaning laion dataset as it have improved performance

**Comment by Zasder3** [comment]
Hi there! Could you elaborate on what you are confused about? Are the image text file titles causing the issue or pretrained model titles?

**Comment by Deadsec69** [comment]
It's image text file titles not pretrained model

**Comment by Zasder3** [comment]
If you use this [tool](https://github.com/rom1504/img2dataset), then it should take care of all naming conventions for you. The file names shouldn't be important to the training routine since we take care of all that for you.
