### ISSUE TITLE
How to use open_clip for duplicate or near-duplicate images?

### ISSUE THREAD

**Issue by smith-co** [mlfoundations/open_clip#113]
Given pair of images, my use case is to detect whether they are duplicate or not.

(imageX, imageY) = verdict/score
verdict = duplicate/not duplicate/near duplicate

How can I use open_clip for this use case?

**Comment by carlini** [comment]
All you need to do is compute the image embeddings for imageX and imageY, normalize them to the l2 ball, and then compute the dot product of the similarity vectors. If the similarity is above some threshold (that you choose) then you count it as duplicated (probably). Following the Usage section from the Readme should show you how to do this, please feel free to raise an issue if you have a specific problem with the code.
