### ISSUE TITLE
Studying the robustness factors of CLIP

### ISSUE THREAD

**Issue by sayakpaul** [mlfoundations/open_clip#119]
From the README:

> Therefore, we can study what makes CLIP robust without requiring industrial-scale compute.

Possible to share relevant reading regarding the studies that show what makes CLIP robust?

**Comment by Zasder3** [comment]
The original paper as well as the the two linked below the figure in the section you mentioned (Taori 2020 & Miller 2021) do a really good job at laying the groundwork for robustness. Why CLIP in specific is so robust is answered in this [paper](https://arxiv.org/abs/2205.01397)!

This is still an open question and point of discussion. Let me know if you have any questions! :)

**Comment by sayakpaul** [comment]
I am aware of the first two papers you mentioned and I agree they help set a foundation for robustness. Thanks for referring me to the other one. Appreciate your help.
