### ISSUE TITLE
Captions of YFCC dirty

### ISSUE THREAD

**Issue by Ascn89** [mlfoundations/open_clip#12]
Hello there,

not really an issue but something i am interested in: How did you clean the captions of YFCC?
I did the steps explained in the closed issue, but still there are a lot of captions with URLs, camera names and settings, dates, and so on. Compared to CC (where the captions are really clean) it looks really bad. Still you get a big jump in performance on ImageNet, so before i start training i would like to know if you did clean the data? 

If so, i would be very happy if you could provide the code or some snippets :)

Best regards

**Comment by gabrielilharco** [comment]
Hi @Ascn89,

The steps you are referring to (https://github.com/mlfoundations/open_clip/issues/7#issuecomment-904077010) are all we did for cleaning the captions in our experiments.

Please note that we use a filtered version of YFCC with only 15M samples, which you can find here: https://github.com/openai/CLIP/blob/main/data/yfcc100m.md

In general, I think noise is less harmful than what we usually think. For instance, ALIGN uses a large, but minimally filtered dataset, and get some pretty decent results (see https://arxiv.org/abs/2102.05918).

Hope this helps!
