### ISSUE TITLE
How much difference does webdataset make for training time?

### ISSUE THREAD

**Issue by TheShadow29** [mlfoundations/open_clip#120]
Hello, thanks for the amazing repository. I see that the repository is using webdataset. I was wondering if you could share some insights on how much training time improvement you get with webdataset vs loading raw images or loading from lmdb / hdf5?

**Comment by rom1504** [comment]
Using shards of reasonable size is a requirement for many file system, it's simply not possible to store 400M files in many of those, including the one in juwels supercomputer, but also many others.

Beyond that, using shards makes it possible to access the disk linearly (the shard is read in order) which is 10 to 100 times faster than random access depending on the drive type.

So the question to answer is really shards vs raw files, and the answer is shards are much better for sequential access patterns.

Webdataset is one way to read shards encoded as tar shards, but tfrecord shards using tf data or parquet shards using petastorms would work as well.

I advise you take a look at img2dataset for preparation of datasets.

Regarding hdf5 and lmdb they can work as well if data is sharded but they are much more complex than tar files so will reduce the number of tools that can use them .

One more piece of information is laion400m is 10TB in 256x256, and laion5B is 240TB in 384x384, sharding that in pieces of 256MB-1GB makes it much easier to move the data around

**Comment by TheShadow29** [comment]
@rom1504 Yes, img2dataset is awesome and I used it to download cc3m. I am preparing a webdataset on my end using tarp for a video dataset so I was wondering if there were some benchmarks for the same.

For instance, how many files should I put within a single tar file, and what kind of speedups is expected. Appreciate your insights.

**Comment by rom1504** [comment]
@TheShadow29 images and videos are pretty different. Images are small and fairly cheap to decode
Video are big and expensive to decode
I advise having shards ranging from 256MB to 4GB depending on your file system

**Comment by TheShadow29** [comment]
@rom1504 You are right. With 3gb shards, for simple dataloading I see 2x speed up if I just read the video (don't decode it), but just 5% speedup if I also decode 4 frames (decoding via decord). In contrast, for cc3m I was noticing almost 10x speed up when using webdataset.

**Comment by rom1504** [comment]
Interesting!
You may be interested by https://github.com/iejMac/video2numpy , a new lib trying to extract frames from videos as fast as possible.
