### ISSUE TITLE
issues about reading CC datasets

### ISSUE THREAD

**Issue by simplelifetime** [mlfoundations/open_clip#122]
Thank you for your incredible work! I'm using your script for downloading the conceptual captions dataset. Obviously some URLs are not accessible. When i run the training script i got the problem:
FileNotFoundError: [Errno 2] No such file or directory: 'cc_data/train/771/71771.jpg'
Is it caused by images that fail to download? Should I rewrite the dataloader to fix these bugs? Thanks!

**Comment by carlini** [comment]
It shouldn't crash in this way. Can you give a full stack trace with the command you ran to get this? Mainly: are you sure that you're running from the right directory that the cc_data folder is in?

**Comment by simplelifetime** [comment]
> It shouldn't crash in this way. Can you give a full stack trace with the command you ran to get this? Mainly: are you sure that you're running from the right directory that the cc_data folder is in?

Thanks for your kind reply, the problem is caused by directory mismatch in the output CSV file. It's already been solved.
