### ISSUE TITLE
Sampling with replacement in webdataset

### ISSUE THREAD

**Issue by penfever** [mlfoundations/open_clip#123]
OBSERVED BEHAVIOR: When the command line argument num_samples is greater than the actual number of samples available for training, it seems webdataset defaults to sampling with replacement, even when resampled = False.

EXPECTED BEHAVIOR: Training ends when the model runs out of samples.

This behavior can be verified by simply training with num_samples > the actual number of samples available for training.

**Comment by rwightman** [comment]
@penfever it should not revert to sampling with replacement, it wraps. I am not aware of a sane way to achieve what you want with WDS and deal with the multiple corner cases w/ distributed training, unbalanced sharding splits, etc.
