### ISSUE TITLE
Where is args.C used?

### ISSUE THREAD

**Issue by viyjy** [mlfoundations/open_clip#125]
https://github.com/mlfoundations/open_clip/blob/6e00e7fff6ec913395319d4aa79dbea889dc3446/src/training/params.py#L249

**Comment by steve-z-seattle** [comment]
By searching the source code, I think it is not used anywhere. But let's see what others have to say. @viyjy

**Comment by viyjy** [comment]
> By searching the source code, I think it is not used anywhere. But let's see what others have to say. @viyjy

Yes, I also searched the code and didn't find it. 
Sure, thanks.

**Comment by gabrielilharco** [comment]
Thanks for raising this, this argument is indeed no longer used and was deleted.
