### ISSUE TITLE
Is it possible to get captions for images?

### ISSUE THREAD

**Issue by 25icecreamflavors** [mlfoundations/open_clip#127]
Can these models provide captions or list of objects that are on the encoded image? Maybe some probabilities with names for objects on the photo?

**Comment by carlini** [comment]
These are [CLIP-style](https://arxiv.org/abs/2103.00020) models. Given an image (or a piece of text) they produce an embedding.

Given an image they won't give you a caption (but if you have a list of candidate captions they can tell you which is best). And given an image they won't directly give you a list of objects (but if you have a list of candidate objects you can ask which of "a picture of a _____" is best).

**Comment by 25icecreamflavors** [comment]
Thank you very much. I think I will just use a big list of objects to get possible candidates.
