### ISSUE TITLE
eot_token after truncating

### ISSUE THREAD

**Issue by liyz15** [mlfoundations/open_clip#130]
I was comparing with the official implementation and find that 

https://github.com/mlfoundations/open_clip/blob/db0429cf256c0fae000bb00a81d40f2675d573ea/src/open_clip/tokenizer.py#L176-L178

is different from [the official implementation](https://github.com/openai/CLIP/blob/b4ae44927b78d0093b556e3ce43cbdcff422017a/clip/clip.py#L229-L232)

```python
    if len(tokens) > context_length:
        if truncate:
            tokens = tokens[:context_length]
            tokens[-1] = eot_token
```

This looks like a bug since we are using the highest id as cls token for text encoder

https://github.com/mlfoundations/open_clip/blob/c933765dc557d88e15be968e78d7580d95f86af8/src/open_clip/model.py#L451

**Comment by Zasder3** [comment]
Good catch! It looks like @rom1504 fixed this in the original OpenAI repo, but the internal version didn't catch on. Will try to amend this soon.
