### ISSUE TITLE
Make it possible to save more often than an epoch

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#135]
one epoch can take 24h

or maybe should I do fake small epochs + resampling ?

**Comment by Zasder3** [comment]
That makes sense to me! My thought is to add a global step counter and potentially seed from its state. Then add the arg `--save_every_n_steps` to CLI.

**Comment by rom1504** [comment]
that's one way @Zasder3 but actually from experience what people really want is not to save every n steps. They usually want to save every n hours. It's important not to lose many hours of training, losing many steps is less obvious (people would usually just count how many hours that is)
maybe we could have save_every_n_hours and a global time counter ?

**Comment by rom1504** [comment]
I'll use --dataset-resampled and decrease number of sample / increase number of epoch for now

**Comment by rwightman** [comment]
@rom1504 after I thought about this a while back, I feel that --dataset-resampled to create your own 'virtual' epochs is the best approach, adding checkpoints support in the middle of the epoch is more logic to add and debug, and it doesn't play well with the non-resampled approach...

**Comment by rom1504** [comment]
I agree, it works fine.
I think we can just add a few lines about this use case in the readme

**Comment by rom1504** [comment]
https://github.com/mlfoundations/open_clip/pull/174
