### ISSUE TITLE
integrate clip benchmark into validation every epoch

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#137]
https://github.com/LAION-AI/CLIP_benchmark

at least for imagenet
it prepares dataset automatically

could be helpful if validation is fast

**Comment by rom1504** [comment]
no, too slow, see issue there for companion script

**Comment by usuyama** [comment]
> too slow

Interesting - @rom1504 can you point me to the issues you mentioned? It seems like a great feature if it can be integrated.
