### ISSUE TITLE
log every n seconds rather than n steps

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#138]
https://github.com/mlfoundations/open_clip/blob/15bb1f7347acdfc2e5e3069455a84fbd188aa4f2/src/training/train.py#L105

steps have varying duration, 100 steps take several minutes for me

**Comment by rwightman** [comment]
could make it an arg so it can be changed for different setups, that's common, measuring time in the loop and having varying # of steps per log is pretty uncommon to see...

**Comment by rom1504** [comment]
Do you think it matters to have constant number of steps between logging time ?

I do think it's important not to have to tune that parameter every training run with different speed.

An alternative solution could be to estimate in the first steps the amount of steps between which to log by measuring time and then keeping it fixed.

**Comment by rom1504** [comment]
added args.log_every_n_steps
good enough
