### ISSUE TITLE
resume broken in torch 1.12

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#140]
hitting https://github.com/pytorch/pytorch/issues/80809

**Comment by rom1504** [comment]
```
                    for g in optimizer.param_groups:
                        g['capturable'] = True
```
 after https://github.com/mlfoundations/open_clip/blob/c933765dc557d88e15be968e78d7580d95f86af8/src/training/main.py#L201 is a workaround
seems to slow down training by 3% but works

**Comment by rom1504** [comment]
doing https://github.com/pytorch/pytorch/pull/80881/files might be a better fix...

putting everything as capturable seems to make things diverge in addition to being slower (to be confirmed)

**Comment by rom1504** [comment]
applied that new fix. Let's see if it's better

**Comment by rom1504** [comment]
that fix worked, but let's still keep this open until they release the fix upstream

**Comment by rwightman** [comment]
@rom1504 I was just gonna say, 'weird, I didn't run into this after setting up 1.12 on JUWELS', but just realized it's 1.12.1 and issue is fixed, upgrade torch :)
