### ISSUE TITLE
is cosine schedule applied properly on resume ?

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#141]
https://github.com/mlfoundations/open_clip/blob/c933765dc557d88e15be968e78d7580d95f86af8/src/training/main.py#L220 doesn't look like it

**Comment by Zasder3** [comment]
I think it is. It's actually returning a function that assigns the lr given the input step. The assignment occurs within the `train_one_epoch`. What differs from your expectations?

**Comment by rom1504** [comment]
https://github.com/mlfoundations/open_clip/blob/c933765dc557d88e15be968e78d7580d95f86af8/src/training/train.py#L71 yeah you're right

**Comment by rom1504** [comment]
![Screenshot_20220801_034254](https://user-images.githubusercontent.com/2346494/182056663-a7212f02-e32a-4bd0-82ec-3a43aef6bae4.png)

I'm seeing that weird loss pattern after resume. Must be something else

**Comment by Zasder3** [comment]
Is the epoch length correctly specified? I'm wondering if it's struggling to estimate the current step.

**Comment by steve-z-seattle** [comment]
I had to resume multiple times during the past month during a long training loop. I think the scheduler is working properly.

**Comment by steve-z-seattle** [comment]
FYI: [https://tensorboard.dev/experiment/HEEi7QWOTQi11cByVNcrag/#scalars&tagFilter=loss%7Clr%7Ctop%7Cepoch](url)

**Comment by rom1504** [comment]
![Screenshot_20220801_085154](https://user-images.githubusercontent.com/2346494/182089472-aee32516-7e86-4d37-89cc-91eed7901f5b.png)

eventually turned into that

![Screenshot_20220801_085339](https://user-images.githubusercontent.com/2346494/182089780-4c34b5f3-d655-4bca-adfa-bdd0688d2168.png)

looks like that with less wandb smoothing

I think everything is fine except for wandb smoothing being weird
