### ISSUE TITLE
Add sha256 checksum for `mlfoundation` released pretrained models

### ISSUE THREAD

**Issue by fabito** [mlfoundations/open_clip#143]
Currently only the pretrained models published on `openaipublic.azureedge.net` have the sha256 checksum verified/matched:

https://github.com/mlfoundations/open_clip/blob/15bb1f7347acdfc2e5e3069455a84fbd188aa4f2/src/open_clip/pretrained.py#L131

I've ran into an [issue](https://github.com/apache/beam/issues/22402) where corrupted models were cached in `~/.cache/clip`.

Can we generate the checksums for the models published in the `mlfoundations` github org as well  ( and then remove the check condition in `download_pretrained`) ?

**Comment by rom1504** [comment]
Sounds good!

If you have some time, feel free to open a pull request for it.

**Comment by rwightman** [comment]
FYI every weight at https://github.com/mlfoundations/open_clip/releases/tag/v0.2-weights has the first 8 char of the sha256 checksum after the last `-` ... which should be plenty for verifying corrupt downloads...

**Comment by fabito** [comment]
Thanks for pointing that out, I'll give it a go.
