### ISSUE TITLE
Confused about the indicator

### ISSUE THREAD

**Issue by jinghaoliu** [mlfoundations/open_clip#149]
Hi, thank you for your great work. But I am confused about the indicator. Could you please tell me what these means when you are convenient? such as: image_to_text_mean_rank, image_to_text_median_rank, image_to_text_R@1, text_to_image_mean_rank

**Comment by carlini** [comment]
All of these have to do with how similar the embeddings of images and their captions are. Let's start out by embedding each image and also its corresponding caption in a minibatch. Then, for each image, compute the similarity between that image's embedding and every caption. Call the "rank" of the correct caption the number of other captions that are more similar than the correct caption. So rank 0 means the inserted image/caption pair are more similar to each other than any other caption is to that image.

image_to_text_mean_rank is the mean of this value across all images in the minibatch. Smaller numbers are better.

image_to_text_R@1 is the fraction of images where the rank is equal to zero. Larger numbers are better.
