### ISSUE TITLE
resuming uses more vram than on first run

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#154]
I noticed it while trying to resume a vit-g-14

would be helpful to investigate why that is and fix it (can just train vit-g-14 for 1 step to have a checkpoint and reproduce)

**Comment by rom1504** [comment]
https://github.com/Nodja/open_clip/commit/8a5ea42d458c7e36e7040d6deb227cc8343f73db is a proposed fix

**Comment by rom1504** [comment]
it's working!

**Comment by rom1504** [comment]
fix pr https://github.com/mlfoundations/open_clip/pull/156/files

**Comment by rwightman** [comment]
@rom1504 yeah, that's the way it should have been done but didn't catch that.. I don't believe the extra model.to is needed though... when you load a CPU state dict into a model that's already on the GPU it should transfer to the GPU at that point....

**Comment by rom1504** [comment]
oh yeah right

**Comment by rom1504** [comment]
fixed the pr

**Comment by rwightman** [comment]
PR merged
