### ISSUE TITLE
Why does ViT-L-14-laion400m_e32 perform worse than ViT-L-14-openai on some zero-shot results?

### ISSUE THREAD

**Issue by Quan-Sun** [mlfoundations/open_clip#161]
I'm wondering why does ViT-L-14-laion400m_e32 perform much worse than ViT-L-14-openai on some zero-shot results.
[LAION-AI/CLIP_benchmark](https://github.com/LAION-AI/CLIP_benchmark/blob/main/benchmark/benchmark.csv).

Would be nice if this repo can add training logs.

**Comment by rom1504** [comment]
We are currently running experiments to understand this better. Including
using a different subset of the dataset and using a bigger dataset.

There are also other possible hypothesis such as non optimal hyper
parameters, and instability.

We'll release more results soon.

**Comment by rom1504** [comment]
Now released!
