### ISSUE TITLE
Expose cache_dir in interface

### ISSUE THREAD

**Issue by samedii** [mlfoundations/open_clip#164]
It would be nice to expose the cache dir in the interface. I've been hacking around this but with the recent update with `pretrained_cfg` this has become even hackier.

```python
        pretrained_cfg = open_clip.pretrained.get_pretrained_cfg(architecture, weights)
        weights_path = open_clip.pretrained.download_pretrained(
            pretrained_cfg,
            cache_dir=my_cache_dir,
        )

        # hack: needed to specify path to weights
        if weights == "openai":
            self.model = open_clip.load_openai_model(
                weights_path, start_device, jit=jit
            ).eval()
            if precision == "fp32":
                model = model.float()
        else:
            self.model = open_clip.create_model(
                architecture,
                weights_path,
                device=start_device,
                precision=precision,
                jit=jit,
            ).eval()

        # hack: since we specified the weights path instead of the model name the config isn't loaded right
        setattr(
            self.model.visual,
            "image_mean",
            pretrained_cfg.get(
                "mean",
                getattr(self.model.visual, "image_mean", None),
            )
            or (0.48145466, 0.4578275, 0.40821073),
        )
        setattr(
            self.model.visual,
            "image_std",
            pretrained_cfg.get(
                "std",
                getattr(self.model.visual, "image_std", None),
            )
            or (0.26862954, 0.26130258, 0.27577711),
        )
```

**Comment by rwightman** [comment]
@samedii FYI you can globally override with env vars as well
`HUGGINGFACE_HUB_CACHE` for hf hub stored models + `TORCH_HOME` for models downloaded from URI via the pytorch mechanism... 

will look at punching that throught the creation api...

**Comment by samedii** [comment]
Good point. This is the default I'm hitting without hacks and I didn't see a way around it.
```
    if not cache_dir:
        cache_dir = os.path.expanduser("~/.cache/clip")
```

If you think it's okay to expose then I can create a PR soon :)

**Comment by rwightman** [comment]
Oh right that overrides the env vars, could just remove that and make it use torch hub or hf hub defaults? AND pass the cache dir through, hmmm. Or make a OPEN_CLIP_CACHE var...

**Comment by samedii** [comment]
Good idea. Those are probably better defaults than the original CLIP's `~/cache/clip`

**Comment by rwightman** [comment]
@samedii missed a case for passing through to the hf hub for the new larger model weights... should be good now

**Comment by rwightman** [comment]
So behaviour now, if cache_dir passed, will be used for any weight dl via hf hub OR download url. If no cache_dir set, download from URL will default to ~/.cache/clip, HF hub downloads will use HUGGINGFACE_HUB_CACHE in env (defaults to a .cache/huggingface/hub folder). I could change the url dl defautl to be same as torch or leave as is for now...

**Comment by samedii** [comment]
@rwightman Ah great catch! Thanks I went a bit too fast

I'm not sure what the best default is but it's of course nicer to not pepper multiple global folders with model weights 😅 I would personally avoid the original CLIP folder but that has "backwards compatibility issues"
