### ISSUE TITLE
how to change the text encoder and fine-tuning on custom dataset? 

### ISSUE THREAD

**Issue by koshinryuu** [mlfoundations/open_clip#170]
I would like to use a custom BERT-based text encoder, how to change it and finetune whole clip on one dataset?

**Comment by rwightman** [comment]
Please see https://github.com/mlfoundations/open_clip/pull/93 ... there is definitely interest in doing this, but it's not so straightforward to get good results

**Comment by rom1504** [comment]
this is possible now
