### ISSUE TITLE
Fp16 or Fp32 in the inference phase?

### ISSUE THREAD

**Issue by pengzhiliang** [mlfoundations/open_clip#171]
Hello~

Thanks for the great work!

And I'd like to know that the impact of using fp16 not fp32 in the inference phase (e.g., the ViT-H-14). I find that all the models in OpenAI clip will convert to fp16 automatically. So does it matter here?

Thank you~
Zhiliang.

**Comment by rwightman** [comment]
@pengzhiliang all of the inference benchmark results here have been done w/ AMP (mixed precision) using autocast. The throughputs seemed comparable to OpenAI's float16. I've tested pure float16 for someof the smaller models and it seemed fine for inference. I have not tested the newer models with that.

bfloat16 would also be an option, there is AMP + bfloat16 support added here recently, you could also cast to pure bfloat16, you'd need to be using professional Ampere cards for good performance with bfloat16 though.

For AMP remember you need to performe the inference under an autocast context...

**Comment by pengzhiliang** [comment]
OK, it solves my concern.
Thank you very much!
