### ISSUE TITLE
multilingual dataset

### ISSUE THREAD

**Issue by shuohan** [mlfoundations/open_clip#172]
Hi,

I wonder if this can be used for multilingual datasets. I read from https://laion.ai/blog/laion-5b/ that there is MCLIP. Is MCLIP available?  Thank you.

**Comment by rom1504** [comment]
hi, you may try https://github.com/FreddeFrallan/Multilingual-CLIP which is a mse-aligned clip text encoder that works for multilingual
for a proper multilingual clip, we need https://github.com/mlfoundations/open_clip/pull/93 to be finished
