### ISSUE TITLE
Intro has wrong package name

### ISSUE THREAD

**Issue by markusMM** [mlfoundations/open_clip#175]
Previously the package name was `òpen_clip_torch`.
Thus, it is stated as this in the `readme.md`.

But the name seem to be changed to `open-clip-torch`!
Thus, it has to be renamed in the `readme.md`.

cheers

**Comment by rwightman** [comment]
@markusMM python packages can' have dashes in the name, only _. pip uses both and displays - in the url, etc by default but converts to _ on use. It makes no difference for pip install.

**Comment by rwightman** [comment]
and FYI the format import package name is open_clip. The torch needed to be added for pypi because there was a conflicting prior use for some dead project.
