### ISSUE TITLE
Resuming while using the same experiment folder

### ISSUE THREAD

**Issue by mehdidc** [mlfoundations/open_clip#180]
Hello,

with @JeniaJitsev we are trying to have an auto-resume script that  continues experiments automatically
when freezing or finishing the reserved time in slurm.
I noticed that when the experiment folder `<logs>/<name>` with `--logs` and `--name`  is specified and re-used in different runs, it raises an error  ("Error. Experiment already exists at "). I have a fork where that error is just ignored, and everything worked fine when auto-resuming, e.g. `out.log` was just extended (append mode) instead of being cleared in each run, same with `results.jsonl` for evaluation.

Is there something I am missing, or could we just allow using the same experiment folder ? if that would work, I could do a PR.
Because that would make things easier, we would have, e.g., a fixed slurm script and we would not need to figure out the resume checkpoint path for each run (using `--save-most-recent`, we would have a fixed path for resuming from the latest checkpoint, i.e. `<logs>/<name>/checkpoints/epoch_latest.pt`), and we would be able to allowed to have one experiment folder per model (if wanted).

**Comment by rwightman** [comment]
@mehdidc 
The exists check and error is there to prevent a mistake where one stomps over a previous run with a new one (ie it'd overwrite old checkpoints, etc if it started from 0) and that could be very undesirable if you just hit run after a 3 week training session and forgot to change and experiment name...

On resume though, we could allow the same eperiment folder to be used. I'm not quite sure what the behaviour with the log output would be, we should verify if it can be appended to vs replaced, or increment a log file suffix or something....

**Comment by rom1504** [comment]
Making sure we do not lose previous training progress is indeed really
important. Having different folders made sure that couldn't happen.

If we go with one folder instead, I think we need to make sure all possible
cases lead to no loss nor overwrite of checkpoints

**Comment by rom1504** [comment]
For wandb one problem that will happen is that it does not allow to edit
past history. So if multiple runs fail for the same steps, nothing will get
logged

**Comment by rom1504** [comment]
If we do several runs in wandb it works indeed. Let's keep doing that.

The issues I was mentioning is the resume feature of wandb which would
continue with the same run. Let's just not use it.

**Comment by rom1504** [comment]
Wandb has a resume option that should be used in that case

**Comment by rom1504** [comment]
I believe this is done now. Is that right @rwightman ?

**Comment by rom1504** [comment]
indeed https://github.com/mlfoundations/open_clip/pull/303

**Comment by rwightman** [comment]
@rom1504 yup, done and working quite nicely  with lots of testing on both stability and juwels over the past week and a bit. I tested extensively with tensorboard

I changed the default wandb resume arg to `auto` @mehdidc @mitchellnw are more likely to have tried this w/ wandb enabled (I tend to use TB). We could tweak that arg if the current behaviour isn't desired...
