### ISSUE TITLE
AttributeError Open CLIP has no attribute "create_model"

### ISSUE THREAD

**Issue by WASasquatch** [mlfoundations/open_clip#183]
I am having issues loading CLIP models suddenly, without any change to our system almost 2 months. I am getting the following error:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-4-145ac54c6c43> in <module>
    509 if RN101: print("Downloading CLIP Model: RN101");clip_models.append(clip.load('RN101', jit=False)[0].eval().requiresgrad(False).to(device))
    510 
--> 511 if ViTB32_laion2b_e16: print("Downloading CLIP Model: ViT-B/32 laion2b_e16"); clip_models.append(open_clip.create_model('ViT-B-32', pretrained='laion2b_e16').eval().requiresgrad(False).to(device))
    512 if ViTB32_laion400m_e31: print("Downloading CLIP Model: ViT-B-32 laion400m_e31"); clip_models.append(open_clip.create_model('ViT-B-32', pretrained='laion400m_e31').eval().requiresgrad(False).to(device))
    513 if ViTB32_laion400m_32: print("Downloading CLIP Model: ViT-B/32 laion400m_e32"); clip_models.append(open_clip.create_model('ViT-B-32', pretrained='laion400m_e32').eval().requiresgrad(False).to(device))

AttributeError: module 'open_clip' has no attribute 'create_model
```

Has this been documented or seen before?

To note, this seems to be happening randomly, like the whole module is crashing. One load of a CLIP model is fine, and the next it says there is no `create_model` method that it previously uses just fine.

**Comment by rwightman** [comment]
@WASasquatch no, no know issues of that sort, I can definitely create many different models without running into that issue. Likely a problem with how the module is being imported, or some symbol conflict due to external code...

**Comment by WASasquatch** [comment]
Yeah, not sure. It had been working fine for a couple of months, no changes to code base or repos. In fact, other repos haven't been updates in months either, this is the only one with active dev on this end. Guided Diffusion development seems dead since Stable Diffusion. The fix is directly importing via path. Not sure what the conflict could be unless Open CLIP is using the same naming convention as CLIP, which wouldn't be good.

**Comment by rwightman** [comment]
@WASasquatch directly import by path? Why would you need to do that vs `!pip install open_clip_torch` `import open_clip` ?

**Comment by WASasquatch** [comment]
Well, that's literally that this topic is about... I don't know. Suddenly open_clip has no method `create_model()` after it is ran for the first time. After that, it can't find the method until you disconnect and delete the VM. Next time, same deal, runs once, then method is gone.

**Comment by rwightman** [comment]
@WASasquatch you have something wrong with your environment / import, 100% not an issue here. open_clip having no method create_model means you haven't imported the open_clip module (or rather that symbol isn't the open_clip module). If it runs once and then not, you've probably stomped over some names or have conditionals / import code that's running different 1st time vs subsequent.

**Comment by WASasquatch** [comment]
That seems very unlikely. The setup cell is independent of the script, and cannot operate on it's own. All that's down, is it is installed, imported, and then ran. 

![image](https://user-images.githubusercontent.com/1151589/193183565-76106973-9fc5-4013-b675-f5e6d8780139.png)

There are the only occurrences of the function, which involves installation and running create model.

**Comment by rwightman** [comment]
@WASasquatch why would you check if path exists, and looks like clone the git and add the path manually when you can just pip install the module? main is up to date with pip...

you probably import correctly the first run through and then import ./open_clip instead of ./open_clip/src/open_clip the next time around or something along those lines, might want to check your control flow

**Comment by WASasquatch** [comment]
Again, the installation cell can't run on its own. And yes, checking if path exists to skip it's install if a user runs the setup cell again to save time. Pretty common...

**Comment by WASasquatch** [comment]
Additionally, installing `pip install open_clip_torch` yields `ModuleNotFoundError: No module named 'open_clip'`

**Comment by rom1504** [comment]
feel free to use the example notebook https://colab.research.google.com/github/mlfoundations/open_clip/blob/master/docs/Interacting_with_open_clip.ipynb

it works fine, I ran it just now

**Comment by rom1504** [comment]
installing from git is not the correct way

**Comment by rwightman** [comment]
@WASasquatch this short demo also works perfectly fine across multiple restarts, there are issues on your end. https://colab.research.google.com/drive/1Fy4bM-goH4xQKIv3ZzQ7fSdYBcT1N9CP?usp=sharing
