### ISSUE TITLE
'amp_bfloat16'  significantly slower than 'amp' and 'fp32'

### ISSUE THREAD

**Issue by ChengJiacheng** [mlfoundations/open_clip#184]
Hi, thank you for the great work!

I tried the newly implemented precision option `amp_bfloat16`, it did improve the training stability in my case. However, I found it to be significantly slower than `amp` and even `fp32`.

I used the script below to train the "RN50" model on 8 A100 40GB GPUs. My observation is that `amp_bfloat16`/`amp`/`fp32` usually takes ~0.73s/~0.28s/~0.35s for a training batch.  

```

LR=1e-4
EP=33
BS=128

MODEL="RN50"

cd src
# python -m training.main \
torchrun --nproc_per_node 8 -m training.main \
        --train-data='.../cc3m_train/{00000..00663}.tar' \
        --train-num-samples 3000000 \
        --imagenet-val "/home/jiachengc/imagenet/val"\
        --dataset-type webdataset \
        --batch-size ${BS} \
        --warmup 10000 \
        --epochs ${EP}  \
        --lr=${LR} \
        --wd=0.1 \
        --precision amp_bfloat16 \
        --workers 4 \
        --report-to "tensorboard" \
        --zeroshot-frequency 2 \
        --model "${MODEL}" \
        --sync-bn \
        --zeroshot-frequency 2 \
        --save-frequency 20 \
        --save-most-recent \
```

However, from [here](https://github.com/mlfoundations/open_clip/pull/158#issue-1361174413) I read that 

> "At large model/data/batch size, float16 amp is not stable with clip training. amp bfloat16 solves this problem while being 20% faster."  

I am not sure do I miss anything?

**Comment by rwightman** [comment]
@ChengJiacheng you don't want to use it if you have convolutions in the network, for VIT models. There aren't bfloat16 conv kernels.

Experimental, but you could also try https://twitter.com/ptrblck_de/status/1570548161533587457

`export TORCH_CUDNN_V8_API_ENABLED=1` in your environment to enable new bfloat16 conv kernels. Not sure if it's in all pytorch releases or requires nightly, or at least a cuda 11.6?

**Comment by ChengJiacheng** [comment]
@rwightman Thanks for the explantion and suggestion! I tried it and it seems to work! Now the training time per batch is reduced to ~0.28s from ~0.73s, quite close to that of `amp`. I will finish the training and see if it affects the training results.

My environment info is as below.
```
>>> torch.__version__
'1.12.1'
>>> torch.version.cuda
'11.3'
>>> torch.backends.cudnn.version()
8302
```
