### ISSUE TITLE
combining jit + autocast seems to make first inference take many minutes

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#188]
I'm wondering if anyone else saw that

trying to do inference

**Comment by rom1504** [comment]
jit does not seem to make things much faster when using autocast, so I'll probably just disable by default

**Comment by iejMac** [comment]
yes I think I recall this happening when we were doing the distillation experiments

**Comment by rwightman** [comment]
so, don't think this is a bug, just jit compilation being slow... and yeah, overall the gains in runtime speed are not worth the compile time, but that looks like it could change in future pytorch codegen
