### ISSUE TITLE
About CC_Data

### ISSUE THREAD

**Issue by daeing** [mlfoundations/open_clip#190]
Dear author, there are some pictures not available in train/val.csv file. Does this matter the training process? Or do you have the full dataset of cc_data? Many thanks.

**Comment by gabrielilharco** [comment]
Hi @daeing! This is a common issue with large-scale image datasets. As is the case for CC, authors sometimes only release the image urls (and not the actual images), so we don't have much control over images that are taken down from the internet after the dataset is created. Unfortunately this means that results aren't typically directly comparable. However, as long as the number of unavailable images isn't too big, I believe this shouldn't have a very large impact on the trained models.

**Comment by rwightman** [comment]
@daeing yeah, this is normal for datasets like cc3m/12m, LAION, etc that specify just the URLs, links become stale and slowly the % of the original dataset you can download decreases.
