### ISSUE TITLE
Hyperparams used to train specific model configs

### ISSUE THREAD

**Issue by vasusharma** [mlfoundations/open_clip#191]
Hi team,
I am trying to reproduce the numbers of your model on the LAION-400M dataset and am not able to reproduce the same numbers. For example, I obtain a 42% imagenet zeros shot top 1 val accuracy compares to the 47% you report with VIT-B32 quickgelu config. Could you share your other hyperparams you used to obtain those results so that I can run the training with the exact same setup, or better yet share the exact command you used to run the training runs specific to the reported results, I would really appreciate that.

**Comment by rwightman** [comment]
Some other hparams ca be found at:
https://huggingface.co/laion/CLIP-ViT-L-14-laion2B-s32B-b82K

Or pieced together from https://docs.google.com/document/d/1EFbMLRWSSV0LUf9Du1pWzWqgeiIRPwEWX2s1C6mAk5c/edit
