### ISSUE TITLE
Avenue for exploration - augmenting training set with colour palettes / texture names /more meta data

### ISSUE THREAD

**Issue by johndpope** [mlfoundations/open_clip#2]
so part of the fun with clip is using it in conjunction with VQGAN.
This allows the prompts to generate images. 

There's something lost in this translation. though .
They say a  picture is worth a 1000 words -  but what if some  extra data was injected into the training ?

could be  say  textures / maybe even  geometric descptions  / meta data

**Comment by mitchellnw** [comment]
We agree that the generations with VQGAN are awesome, however they are currently outside of the scope of this repo.

We are, however, looking into adding more data during training.
