### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by tss-happens** [mlfoundations/open_clip#201]
hi im experiencing such error when launching disco diffusion:

File /workspace/open_clip/src/open_clip/tokenizer.py:12, in <module>
      9 from typing import Union, List
     11 import ftfy
---> 12 import regex as re
     13 import torch
     16 @lru_cache()
     17 def default_bpe():

ModuleNotFoundError: No module named 'regex'

**Comment by rwightman** [comment]
@tss-happens install the module
