### ISSUE TITLE
args.hf_model_name might be confusing?

### ISSUE THREAD

**Issue by usuyama** [mlfoundations/open_clip#210]
I think hf-model-name argument is only used for setting hf_tokenizer_name

```
    if getattr(args, 'hf_tokenizer_name') is None:
        setattr(args, 'hf_tokenizer_name', args.hf_model_name)
```

Currently, to specify the huggingface text model, we need to set hf_model_name in the config json file e.g. `model_configs/roberta-ViT-B-32.json`

I wonder if it's better to either (1) overwrite the model_cfg if args.hf_model_name is given or (2) remove args.hf_model_name to avoid confusion.
It's bit tricky to use correct text encoder and tokenizer pairs.

**Comment by rwightman** [comment]
hmm, yeah, probably should not have an arg for that.. @iejMac is there a reason why the hf_model is in the arg, seems like it'd make more sense for it to always be specified by config

**Comment by rom1504** [comment]
Agreed we should remove that arg

**Comment by usuyama** [comment]
I can send a quick PR.

**Comment by rom1504** [comment]
https://github.com/mlfoundations/open_clip/pull/215 does it, how does that look ?
