### ISSUE TITLE
release roberta b/32

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#217]
so I trained a roberta b/32 clip, perf are reasonable (better on a few tasks that need better text understanding)
should we release it by storing in HF?

**Comment by rom1504** [comment]
I'd appreciate some help there @iejMac or @rwightman 
not sure how to generate these files https://huggingface.co/laion/CLIP-ViT-B-32-laion2B-s34B-b79K/tree/main ; in particular [preprocessor_config.json](https://huggingface.co/laion/CLIP-ViT-B-32-laion2B-s34B-b79K/blob/main/preprocessor_config.json)

**Comment by iejMac** [comment]
I also am not sure about this but couldn't you just copy over that preprocessor_config.json? whatever it does it looks like it probably shouldn't change for the roberta model since the image encoder is the same.

@rom1504

**Comment by rom1504** [comment]
Oh yeah i linked the wrong file
I meant all the files related to the tokenizer

**Comment by iejMac** [comment]
hmm maybe tokenizer_config.json is for non-hf tokenizers and since Roberta uses a hf tokenizer you can just get by with copying over tokenizer.json from here https://huggingface.co/roberta-base/tree/main
