### ISSUE TITLE
timm: unknown model convnext_xlarge

### ISSUE THREAD

**Issue by lopho** [mlfoundations/open_clip#219]
I'm currently writing CI tests against all configs (as listed by `list_models()`).

The following are listed but unavailable:
- timm-vit_medium_patch16_gap_256
- timm-convnext_xlarge

Unless it was an oversight, let me know if it will take some time until they are ready,
so I can add exceptions to the tests until then.

Using timm 0.6.11 from pypi.
```py
open_clip.list_models()
# [..., 'timm-convnext_xlarge', ..., 'timm-vit_medium_patch16_gap_256', ...]
open_clip.create_model('timm-convnext_xlarge')
```
```
...
    model = open_clip.create_model(
  File "/.../open_clip/src/open_clip/factory.py", line 197, in create_model_and_transforms
    model = create_model(
  File "/.../open_clip/src/open_clip/factory.py", line 149, in create_model
    model = CLIP(**model_cfg, cast_dtype=cast_dtype)
  File "/.../open_clip/src/open_clip/model.py", line 159, in __init__
    self.visual = _build_vision_tower(embed_dim, vision_cfg, quick_gelu, cast_dtype)
  File "/.../open_clip/src/open_clip/model.py", line 77, in _build_vision_tower
    visual = TimmModel(
  File "/.../open_clip/src/open_clip/timm_model.py", line 42, in __init__
    self.trunk = timm.create_model(model_name, pretrained=pretrained)
  File "/.../lib/python3.9/site-packages/timm/models/factory.py", line 67, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (convnext_xlarge)
```

**Comment by rwightman** [comment]
@lopho in released timm that model only exists as a in22k fine-tuned variant, but that's changing in a coming PR, I left in here as I was testing locally and on JUWELS with the timm branch... 

possible to mask out the test for now? it will be in timm within a week...

**Comment by lopho** [comment]
No problem, I have excluded them for now, will keep an eye on this and reenable them once they're in.
