### ISSUE TITLE
add context_length to model configs that us HF models (and as param to HFTokenizer)

### ISSUE THREAD

**Issue by iejMac** [mlfoundations/open_clip#222]

**Comment by rom1504** [comment]
sure why not

**Comment by iejMac** [comment]
btw, I'm not sure if this is urgent so I've been putting it off. If people need this soon I can push it up the priority queue

**Comment by rom1504** [comment]
we noticed that some models that use relative positional embeddings (eg mt5) do not have a limited context length.

That's an edge case to take into account here
