### ISSUE TITLE
Use random xlm roberta / roberta in test inference

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#234]
to speed up tests

cc @lopho if you feel like looking into it

**Comment by lopho** [comment]
Do you mean picking one xlm roberta config at random and only testing that?
Are a lot of configs going to be added soon?
Alternatively one could always add more runners if the CI is taking too long.

**Comment by rom1504** [comment]
No i meant the existing models (3 of them) are all downloading weights in CI now because they default to pretrained
We could make it so the tests use non pretrained to get some time

Not very prioritary though

**Comment by lopho** [comment]
There are two types of test that download from HF.
`test_pretrained_text_encoder` and `test_inference_with_data`
The name of `test_pretrained_text_encoder` implies that it should test pretrained weights.
Should this one also test on a random initialized model?

**Comment by lopho** [comment]
I've gone ahead and implemented it. #235
