### ISSUE TITLE
mt5 encoder support

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#238]
https://huggingface.co/docs/transformers/model_doc/mt5#transformers.MT5EncoderModel

**Comment by rom1504** [comment]
not sure if we can do this with current impl https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/hf_model.py#L89

**Comment by rom1504** [comment]
I think we need `MT5EncoderModel.from_pretrained` directly in the code

or maybe expand their AutoModel

**Comment by iejMac** [comment]
started working on something here https://github.com/mlfoundations/open_clip/pull/239

we should be able to just use the config.is_encoder_decoder parameter and if it's true set transformer to transformer.encoder

open questions are:
- does every model config have the is_encoder_decoder attribute
- does every encoder-decoder model store the encoder as self.encoder
- what needs to be set in arch_dict for mt5

**Comment by rom1504** [comment]
See https://github.com/huggingface/transformers/blob/v4.24.0/src/transformers/models/mt5/modeling_mt5.py#L91

I don't think we can simply do .encoder

**Comment by rom1504** [comment]
now done
