### ISSUE TITLE
Fix stochasticity in tests

### ISSUE THREAD

**Issue by iejMac** [mlfoundations/open_clip#245]
Some tests seem to pass/fail arbitrarily. Inference test seems to be the culprit:
```
=================================== FAILURES ===================================
_________ test_inference_with_data[timm-swin_base_patch4_window7_224] __________
```

**Comment by lopho** [comment]
I've done all I could come up with to make the random initialization deterministic. See `test/util_test` `seed_all()`. It's also reseeding for each test.

My best guess is, that the machines that are provisioned for the GH runner differ wildly.
I've already added a margin of 4x fp32 resolution for the testing procedure.
It works most of the times, but if it still fails, it should maybe rerun the test.

**Comment by lopho** [comment]
An alternative would be to use either pretrained wieghts, or store the randomly initialized models used to generate testing data as well, this would explode the data size and require storage outside of the repository.

**Comment by rom1504** [comment]
I think it's ok for now, let's see how often it fails
if it's 1/1000 maybe it's not overcomplicate

**Comment by lopho** [comment]
https://github.com/pytorch/pytorch/issues/15359
It seems determinisim accross different CPU families/arches/torch releases is impossible with torch.

I'm suspecting that the tests only pass due to the random models output being mostly flat and within tolerance, which would render them moot.

The only real solution I see here is to use pretrained weights again.
Those could be cached to an extent. Up to 10GB total cache space is given per github project.

**Comment by lopho** [comment]
Another alternative
1. random initializing
2. getting the state_dict
3. setting all values using a custom deterministic inizialization function / or a static values (ex. 0.5)

**Comment by lopho** [comment]
Static initialization does not fix the problem.
It helps to amplify it, and confirms my initial suspicion that torch is not behaving deterministic across processor families.
(ex. AVX vs AVX512)

Testing run with static initialization of all float tensors to fill 0.125
https://github.com/lopho/open_clip/actions/runs/3556373268/jobs/5973694278
example from this run, ViT-L-14-280:
expected: `[13.4732, ..., 13.4732]`
actual: `[5.2760, ..., 5.2760]`

All model configs fail like this, some with smaller/larger margins, but all significant.

Next approach is to generate test data on the fly & on the same machine
- check out the last release tag, ex. v2.7.0
- generate test data
- check out HEAD
- test HEAD against data from tag

It's a bit convoluted in combination with parallel runners.

This will double the run time, but should fix all determinism problems.

**Comment by lopho** [comment]
It works and is not terribly slow, but the workflow file is getting a bit complicated now.

The commit to test against would have to be manually set with each new release.

Workflow run with on-the-fly test data from v2.7.0 (+ pretrained_hf commit) against HEAD:
https://github.com/lopho/open_clip/actions/runs/3557146945/jobs/5974964303

I'll open a PR.

**Comment by lopho** [comment]
see #260
