### ISSUE TITLE
adding coca-pytorch to open_clip

### ISSUE THREAD

**Issue by gpucce** [mlfoundations/open_clip#254]
In [this comment](https://github.com/lucidrains/CoCa-pytorch/issues/2#issuecomment-1320707789) by @rom1504 it has been mentioned the possiblity to add [coca-pytorch](https://github.com/lucidrains/CoCa-pytorch/) to this repo to train a version of it, if nobody is doing it and it is still interesting I could try and set it up. Would it be ok?

**Comment by rom1504** [comment]
That would definitely be great!
If you do that i can try to train it

**Comment by usuyama** [comment]
That would be awesome!

Even greater if it can be implemented in a modular way - related discussions #218

**Comment by rom1504** [comment]
done
