### ISSUE TITLE
Investigate memory usage for HF models

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#261]
mt5 xl non frozen + H/14 frozen uses > 40GB at batch size 1
that seems wrong, something is probably off

**Comment by usuyama** [comment]
Hmm, 40GB seems a lot with batch size 1. Do you use AMP and grad-checkpointing?

FYI - Rough estimates from my quick testing (only text encoder):
<img width="1214" alt="CleanShot 2022-12-02 at 01 08 05@2x" src="https://user-images.githubusercontent.com/344133/205257119-315bb13d-7042-4f76-b028-d08a3b8e7378.png">

**Comment by rom1504** [comment]
yeah using all of that.
Pretty sure there is a bug specifically for the encoder-decoder models coming from HF! (so xlm roberta is fine, mt5 is not)

If you test it out with openclip (even training on one a100 just to reproduce), I'd be interested
