### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#266]
Readme is too big and mention many unrelated things

Let's try and make things simple and move additional information to other MD files

Readme should contain only:
* Best results and models
* How to install
* How to do inference
* how to do training

Details can be moved to dedicated files eg evaluating.md wide-ft.md hf_model.md etc

**Comment by rom1504** [comment]
actually rereading the readme, I think it's pretty clear as is

**Comment by usuyama** [comment]
haha, yea, the current README is not so bad!

I would say it might be great to have a table of pretrained models (ckpt link, model arch, dataset, scores). On a related note, I wonder if we can generate a result csv like this: https://github.com/rwightman/pytorch-image-models/blob/main/results/results-imagenet.csv

**Comment by ludwigschmidt** [comment]
I agree, a table like that would be great to have.

**Comment by rom1504** [comment]
looking at this again, I think it would really help to have a much shorter readme, and move all the details to another file

**Comment by rom1504** [comment]
well actually, I don't know what to remove
