### ISSUE TITLE
Replace eval() with json.load()

### ISSUE THREAD

**Issue by carlini** [mlfoundations/open_clip#28]
AAAaaaaaaaaahhhhhhhhhhhhhhhhhh!!!!!!!

https://github.com/mlfoundations/open_clip/blob/91f6cce16b7bee90b3b5d38ca305b5b3b67cc200/src/training/data.py#L59

**Comment by gabrielilharco** [comment]
thanks! This is fixed in be36164ad7b7f33540e28d2bbb58a21552dd684a.
