### ISSUE TITLE
Better Hugging Face integration -- library tag, community models

### ISSUE THREAD

**Issue by rwightman** [mlfoundations/open_clip#290]
I've been chatting with @LysandreJik about getting OpenCLIP it's own library tag for the HF Hub to improve searchability, allow better tracking of use, etc (ie transformers is https://huggingface.co/models?library=transformers). 

This is possible, but has one blocker, we need to support here for 'community models', by that I mean models that the user community can publish on the hub without any corresponding code changes in OpenCLIP. Right now only built-in models are supported for pretrained weighs. 

`timm` was also orignially built-in model focused, but I added support for hub based models so that via factories one can do `create_model('hf-hub:myorg/myclipmodelid')` which would load both the model config & weights from the hub (instead of just the weights for the builtin)

We'd need a config file format, since we're already using JSON for the builtin model configs this should be easy, we can add a another level, put model configs under a key, and any other needed info (currently a few models customize preprocess settings) under other keys

Something like
``` json
{
  "model_cfg": {
      "embed_dim": 512,
      "vision_cfg": {
          "timm_model_name": "convnext_base",
          "timm_model_pretrained": false,
          "timm_pool": "",
          "timm_proj": "linear",
          "image_size": 224
      },
      "text_cfg": {
          "context_length": 77,
          "vocab_size": 49408,
          "width": 512,
          "heads": 8,
          "layers": 12
      }  
   }
  "preprocess_cfg": {
    "mean": [0.5, 0.5, 0.5]
    "std": [0.5, 0.5, 0.5]
  }
}
```

Transformers models int he hub use `config.json` for their config, since we have some repos already where open_clip + transformers co-exist we'd need a different name, `open_clip_config.json` to match the weight naming would make sense? We could also check that and fall back to config.json if it's an open_clip only repo but that could get confusing... 

Any concerns? @rom1504 @mitchellnw @gabrielilharco

**Comment by rom1504** [comment]
I think that sounds great.

Should it also help to better support on HF clip models that use an HF text
encoder ?

**Comment by rwightman** [comment]
@rom1504 from this point, CLIP models could be supported better in the Hub UI by also adding a community inference pipeline

To get them natively in Transformers, that's another step. I don't think CLIPModel is the path. @NielsRogge that this model would be a good fit https://huggingface.co/docs/transformers/model_doc/vision-text-dual-encoder as it creates both towers from existing Transformers models .. 

I'm not sure if our current use would slot right into that (if it's builtin vit), or if any of the integration we do (handling pooling, etc) needs extra support https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/hf_model.py#L101

If the `timm` vision tower experiments pan out, maybe timm models could be added to dual encoder as well at some point.

**Comment by gabrielilharco** [comment]
I also think it's a great idea, this would likely make open_clip more useful to the community and add some extra visibility
