### ISSUE TITLE
Bug in gather_cc

### ISSUE THREAD

**Issue by Ascn89** [mlfoundations/open_clip#3]
Hi there,

first of all thanks for the code, i appreciate your effort!

I think there is a bug in `gather_cc.py`: 
In line 86 there is a hardcoded `'val'`, which should probably be `split`.

**Comment by mitchellnw** [comment]
Thank you so much for pointing this out!

Fix is made :) https://github.com/mlfoundations/open_clip/blob/main/src/data/gather_cc.py#L86
