### ISSUE TITLE
HF text-tower gives NaN with amp / fp16

### ISSUE THREAD

**Issue by kahnchana** [mlfoundations/open_clip#302]
Training models with HF text-towers gives a NaN. The NaN in loss comes from the first step.

```
torchrun --nproc_per_node 4 -m training.main \
    --train-data "${ROOT}/data/cc12m/{00000..01242}.tar" \
    --train-num-samples 10968539 \
    --dataset-type webdataset \
    --batch-size 1024 \
    --precision amp \
    --grad-checkpointing \
    --workers 4 \
    --imagenet-val "${ROOT}/data/imagenet/val/" \
    --model "mt5-base-ViT-B-32"
```

This does not happen if you set the precision to FP32 (keeping everything else the same). I am wondering if this is due to some error on the model loading. Or some mistake in the way I'm running this. Has anyone else faced this issue?

**Comment by rom1504** [comment]
I did not observe that with xlm roberta

indeed there is an issue with mt5

**Comment by Svithjod** [comment]
Hi, don't know if you have solved the problem, I think it might be related to [this](https://github.com/huggingface/transformers/pull/10956) pull request. I solved the similar **NaN loss** problem with **t5** model when using **amp_bf16** precision here.
