### ISSUE TITLE
ImageNet mean/std for timm pretrained weights

### ISSUE THREAD

**Issue by usuyama** [mlfoundations/open_clip#311]
Currently, I think we're using [OpenAI mean/std](https://github.com/mlfoundations/open_clip/blob/694554495aedf97ac046e53a690ecd86aee96274/src/open_clip/constants.py#L1) even for timm pretrained image models.

Better to use [ImageNet mean/std](https://github.com/rwightman/pytorch-image-models/blob/18ec173f95aa220af753358bf860b16b6691edb2/timm/data/constants.py#L3) for image models that were pretrained with imagenet.

**Comment by rwightman** [comment]
@usuyama you are correct, if a timm pretrained weight is used, especially with locked image tower you want to use the timm mean/std. In most cases though, for timm models I've been training froms scratch where it's fine to use the default. It can be overridden via the command line or in the pretrained weight dict. 

If it was automatically set to the timm value when pretrained weights were used, would that help or confuse people? Once the model was trained they'd need to remember and I don't know if I want to use the timm value by default for from scratch training.

**Comment by usuyama** [comment]
Thank you for confirming!

Yes, we got confused too at first. It'd be best if we can save those important preprocessing params as part of the models, but not sure what's the best way.

I'm okay with the current state though because (1) hope this issue serves as warning (2) it's somewhat minor scenario (starting from timm pretrained weights)

**Comment by gabrielilharco** [comment]
We have support for this now
