### ISSUE TITLE
Flash attention 

### ISSUE THREAD

**Issue by SimJeg** [mlfoundations/open_clip#317]
Hello, 

Flash attention ([paper](https://arxiv.org/abs/2205.14135)) is a fast, memory-efficient and exact implementation of attention. It could speed up training and inference of ViT-B to ViT-g models by a factor 1.5 to 2 (see [xformers README](https://github.com/facebookresearch/xformers)). 

It has already been integrated into the core pytorch library and can be enabled using the experimental flag flash_sdp_enabled (see [here](https://pytorch.org/docs/stable/_modules/torch/backends/cuda.html#flash_sdp_enabled)).

Is there any plan to integrate it to open_clip and timm ?

Thanks,
Simon

**Comment by rom1504** [comment]
seems interesting, how can flash_sdp_enabled be enabled ?

**Comment by SimJeg** [comment]
There is no documentation so far, I tried "with
torch.backend.cuda.sdp_kernel()" but it did not work, need a bit more
investigation. First you need to replace the Attention module from timm by
nn.MultiheadAttention but replace f(x) by f(x,x,x)[0] in the forward pass).

Le jeu. 29 déc. 2022, 00:06, Romain Beaumont ***@***.***> a
écrit :

**Comment by rom1504** [comment]
Already used https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/transformer.py#L176

**Comment by SimJeg** [comment]
@rom1504 thus flash attention will come for free with pytorch 2.0 :) (see [issue #81434](https://github.com/pytorch/pytorch/pull/81434))

**Comment by fabiozappo** [comment]
Hi, is there any update regarding the speed up of CLIP models by using flash attention? I checked the repo but I can't find any reference to it except this issue

**Comment by Haoxiang-Wang** [comment]
In the latest pytorch-nightly release (>=2.0), the FlashAttention is implemented in 
+ `torch.nn.functional.scaled_dot_product_attention` ([doc](https://pytorch.org/docs/master/generated/torch.nn.functional.scaled_dot_product_attention.html)): a new function (of PyTorch 2.0) that OpenCLIP doesn't use
    + For this function, FlashAttention is used as `torch.backends.cuda.flash_sdp_enabled()==True` (the function is to check if the flag is marked True), which can be manually enforced by calling `torch.backends.cuda.enable_flash_sdp(True)` -- on my Ubuntu machine with torch 2.0 & A6000, this flag is enabled by default (no need for manual override), but I don't know how it goes for others.
+ `torch.nn.MultiheadAttention` ([doc](https://pytorch.org/docs/master/generated/torch.nn.MultiheadAttention.html)): the module that OpenCLIP uses
    + For this module, FlashAttention is only enabled when multiple conditions are met, including: 
        1. computing self-attention rather than cross-attention (CoCa has a cross-attention module while all other models in OpenCLIP use self-attention only)
        2. in the inference mode (under `torch.no_grad()` and `model.eval()` together)
        3. auto-cast is disabled (AMP with bfloat16/float16 violates this condition)
        4. and several other conditions, which the OpenCLIP codebase doesn't need to worry
    + Overall, these conditions are too restrictive, so **the use of `nn.MultiHeadAttention` in OpenCLIP does not enable FlashAttention in MOST cases (e.g., during training or when using mixed precision)**.

Therefore, **the current OpenCLIP codebase basically doesn't enjoy the speedup of FlashAttention** in the era of PyTorch 2.0. @rom1504 @SimJeg 

I would strongly encourage the OpenCLIP team to adapt the current attention implementation to the new `torch.nn.functional.scaled_dot_product_attention`. Based on [a recent PR by HuggingFace ](https://github.com/huggingface/diffusers/pull/2303) (see the WIP Benchmark part of this PR ), adapting to `scaled_dot_product_attention` indeed speeds up a lot comparing with the vanilla pytorch attention. Furthermore, when coupling with the new `torch.compile` function, users can gain more speedup -- so I also suggest the adoption of `torch.compile` into OpenCLIP. @Zasder3  @rwightman  @Vaishaal

## References: Usage of PyTorch's FlashAttention implementation in other PyTorch codebases
1. Andrej Karpathy's nanoGPT: https://github.com/karpathy/nanoGPT/blob/a82b33b525ca9855d705656387698e13eb8e8d4b/model.py#L53-L73
2. HuggingFace's diffusor: https://github.com/huggingface/diffusers/pull/2303

**Comment by rom1504** [comment]
I think the easiest is that you would open a PR for it

**Comment by rwightman** [comment]
@Haoxiang-Wang I think you are mistaking re nn.MultiHeadAttention, it uses the same public scaled_dot_product_attention method, that is separate (but overlapping) with the 'fast path' that is more restrictive (no training, etc). I feel if you implemented it manually and compare with nn.MHA you'd see the same performance.

**Comment by Haoxiang-Wang** [comment]
Let me dig into this deeper and see if `scaled_dot_product_attention` brings more speedup vs. `nn.MultiHeadAttention` @rwightman 

I will open a new PR if this new implementation is indeed effective. @rom1504

**Comment by DtYXs** [comment]
> Let me dig into this deeper and see if `scaled_dot_product_attention` brings more speedup vs. `nn.MultiHeadAttention` @rwightman
> 
> I will open a new PR if this new implementation is indeed effective. @rom1504

Hello, I met the same problem. The Doc says `nn.MultiheadAttention` will not use `FlashAttention` when training.

**Comment by EIFY** [comment]
@DtYXs In PyTorch >=2.0 "slow path" of `nn.MultiheadAttention` does [eventually call `scaled_dot_product_attention`](https://github.com/pytorch/pytorch/blob/546e5358020620b688a47f1cfce0b3804b826b60/torch/nn/functional.py#L5441) as long as `need_weights is False`, which is [the case for us](https://github.com/mlfoundations/open_clip/blob/fa38faf5c20b17254ad92829a8ec5de588c08c25/src/open_clip/transformer.py#L182). It may be a bit confusing but "fastpath" is inference-only and unrelated to FlashAttention: basically what @rwightman said.
