### ISSUE TITLE
Embedding sequence of images into CLIP

### ISSUE THREAD

**Issue by justlike-prog** [mlfoundations/open_clip#324]
Hi,

Is there a way to use CLIP to embed whole albums of photos and then check similarity with certain phrases on what the album is about? I have a hard time to think about how I would encode a sequence of images into CLIP? Maybe there are some papers about it out there?

Thanks for any suggestion!

**Comment by rom1504** [comment]
Hi, a simple solution is to take the average of the image embeddings

A better solution is to train on such (set of images, text) an attention
Pooler on top of clip embeddings

**Comment by justlike-prog** [comment]
Yeah I will try with the average first. 
The second idea sounds interesting, could you eloborate in more detail? What is an attention pooler?

**Comment by rom1504** [comment]
https://github.com/mlfoundations/open_clip/blob/30fda531df3edc87eef0421f904604d3033a77bf/src/open_clip/modified_resnet.py#L58 that's one example of implementation
ie using a few layers of attention to merge the embeddings

**Comment by justlike-prog** [comment]
alright, thanks. I will look into it.
