### ISSUE TITLE
How do you scale training to so many GPUs? Will bandwidth become bottleneck?

### ISSUE THREAD

**Issue by SCZwangxiao** [mlfoundations/open_clip#325]
I've tried to finetune your model using 64 GPUs. However, I found that communication between machines becomes the bottleneck of training. Specifically, when I increase the number of machines, the eta increased.

Could you share the training techniques with me?

**Comment by rom1504** [comment]
Indeed multi GPUs training requires using a cluster with fast interconnect (eg more than 50Gbps) between nodes like infiniband or EFA.

**Comment by rom1504** [comment]
Indeed multi GPUs training requires using a cluster with fast interconnect (eg more than 50Gbps) between nodes like infiniband or EFA.

**Comment by SCZwangxiao** [comment]
I see, my cluster only has a 10Gbps interconnect. lol.

**Comment by rom1504** [comment]
It can probably still be made to work!

I actually managed to run openclip on a 10Gbps interconnect cluster a year ago.

Make sure you're using webdataset for the data, and local loss option

**Comment by SCZwangxiao** [comment]
> It can probably still be made to work!
> 
> I actually managed to run openclip on a 10Gbps interconnect cluster a year ago.
> 
> Make sure you're using webdataset for the data, and local loss option

Thank you! We have migrated to a better cluster with Infiniband. The training scales very well.
Btw, Webdataset is incredible, through which we finally achieved on-the-fly accurate video decoding.
