### ISSUE TITLE
Example of inference with open_clip

### ISSUE THREAD

**Issue by mitchellnw** [mlfoundations/open_clip#33]
Would be nice to provide an example of loading a model and performing inference on a single example.

**Comment by mitchellnw** [comment]
Thought it might be easier to just re-use OpenAI's interface here https://github.com/openai/CLIP

If you have an open_clip checkpoint saved at the path `open_clip_checkpoint_pth` you can run the following code to store an OpenAI CLIP compatible checkpoint at `clip_checkpoint_pth`
```
import torch
open_clip_cp = torch.load(open_clip_checkpoint_pth)
open_clip_sd = {k[7:]:v for k, v in open_clip_cp['state_dict'].items()}
torch.save(open_clip_sd, clip_checkpoint_pth)
```
now you can use OpenAI's API
```
import clip
model = clip.load(clip_checkpoint_pth)
```

**Comment by rom1504** [comment]
Could be nice to add that info in the readme

**Comment by mitchellnw** [comment]
good point will do
