### ISSUE TITLE
OpenAI's CLIP not open source?

### ISSUE THREAD

**Issue by UFO-101** [mlfoundations/open_clip#34]
I'm confused about this project. Isn't OpenAI's CLIP already open source?

The repo has an MIT license: https://github.com/openai/CLIP

**Comment by carlini** [comment]
OpenAI's project is an open source implementation that allows you to *use* CLIP. This project is an open source (re)implementation that allows you to *train* CLIP.

**Comment by UFO-101** [comment]
I see, thanks!

At risk of going off-topic, does that mean the trained models/weights that OpenAI has released are also MIT license?

**Comment by carlini** [comment]
We're not affiliated with OpenAI, I'd probably go and ask them that question.
