### ISSUE TITLE
Can CLIP be trained on Windows?

### ISSUE THREAD

**Issue by romesa-khan** [mlfoundations/open_clip#37]
Hi,

Thanks for the tremendous effort!

Is it possible to set up this training code, for fine-tuning CLIP on a custom dataset, on a Windows 10 machine?

**Comment by carlini** [comment]
Custom dataset: yeah definitely. All you need to do is make a CSV with rows that have a path to an image on disk, and a string for the caption. You can see an example for how to construct such a dataset here

https://github.com/mlfoundations/open_clip/blob/main/src/data/gather_cc.py

On Windows 10: I don't know if anyone has tested this before. If you get it working it would be great if you could also submit a PR with steps to reproduce in case anyone else wants to try as well.

**Comment by romesa-khan** [comment]
Thanks for the help! 
I would try to shift to a Linux system for now, in the interest of time.
