### ISSUE TITLE
Loading only the image encoder

### ISSUE THREAD

**Issue by raunak-agarwal** [mlfoundations/open_clip#383]
Is there an easy way to load only the image encoder into the GPU? I couldn't find anything in the prior issues. Thx!

**Comment by rwightman** [comment]
@raunak-agarwal there is no easy as in done for you way to achieve that, with a bit of hacking it's not too hard to achieve (instantiate a vision tower and load just the vision weights from the state dict).

For each of the 'best' checkpoints there is support in `timm` for loading just the image tower as a timm model, 

These models here cover the ViT variants for LAION2B and OpenAI weights, the final projecection layer is mapped to the classifier:
https://github.com/rwightman/pytorch-image-models/blob/2bbc26dd82d1090b26e74d69c97d6a1aaa3757eb/timm/models/vision_transformer.py#L1012-L1046

ex
```python
model = timm.create_model('vit_huge_patch14_clip_224.laion2b', pretrained=True)
embeddings = model(torch.randn(2, 3, 224, 224)
print(embeddings.shape) # [2, 1024]
embeddings = F.normalize(embeddings, dim=-1)  # if you want to normalize as done in common CLIP use
```

You can also remove the final projection layer and output the penultimate features

```python
model = timm.create_model('vit_huge_patch14_clip_224.laion2b', pretrained=True, num_classes=0)
embeddings = model(torch.randn(2, 3, 224, 224)
print(embeddings.shape) # [2, 1280]
```

Or also disable token / pooling and get the sequence
```python
model = timm.create_model('vit_huge_patch14_clip_224.laion2b', pretrained=True, num_classes=0, global_pool='')
embeddings = model(torch.randn(2, 3, 224, 224)
print(embeddings.shape) # [2, 257, 1280]
```
