### ISSUE TITLE
`is_clip` will fail if enable `torchscript`

### ISSUE THREAD

**Issue by wjfwzzc** [mlfoundations/open_clip#395]
https://github.com/mlfoundations/open_clip/blob/191d138296d6749396b2b15e5c3c9459b05e65b3/src/training/train.py#L41-L42

`type(model)` will be `torch.jit._script.RecursiveScriptModule`, `isinstance` will also fail. A compromise solution is to check `model.original_name` when `model` is a `ScriptModule`.

**Comment by rwightman** [comment]
@wjfwzzc should be a non-issue now, tx
