### ISSUE TITLE
CoCa with accum-freq

### ISSUE THREAD

**Issue by usuyama** [mlfoundations/open_clip#418]
Thanks for integrating CoCa!

When I tried coca with --accum-freq 2, I got this error:

```
  File "open_clip/src/training/main.py", line 426, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "open_clip/src/training/train.py", line 141, in train_one_epoch
    model_out = model(images, texts, output_dict=True)
  File "... python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_dict'
```

Looks like an easy fix by adding output_dict arg to CoCa models, but do you think if there will be other issues? @iejMac @rom1504

**Comment by iejMac** [comment]
@usuyama nice catch. Hmm yeah I don't currently see a cleaner way of solving this than just adding output_dict as an unused param to CoCa forward. @rom1504, @gpucce any ideas?
