### ISSUE TITLE
Augmentation configurations for trained models

### ISSUE THREAD

**Issue by jn2clark** [mlfoundations/open_clip#439]
Hi! I was wondering if the training configs for the augmentation settings are available? I could not seem to find them. Specifically, the configurations for the convnext models (e.g. CLIP-convnext_base_w-laion2B-s13B-b82K-augreg, CLIP-convnext_base_w-laion2B-s13B-b82K-augreg). Thanks!

**Comment by rwightman** [comment]
@jn2clark thanks for reminding me, I have to go back and update the base augreg model args (it was still hardcoded then)

In large I added the arg line (https://huggingface.co/laion/CLIP-convnext_large_d.laion2B-s26B-b102K-augreg) ... same as base

`--aug-cfg use_timm=True scale='(0.33, 1.0)' re_prob=0.35 `

And for regularization, in the model config, you should double check that drop_path_rate (stochastic depth) is set (for timm models only right now, don't have stochastic depth in the ViT models yet but we should probably try it): https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model_configs/convnext_base_w.json#L9

**Comment by jn2clark** [comment]
Awesome, thanks @rwightman !

**Comment by sagadre** [comment]
@rwightman wondering why there are special augmentations for convnext that are not typically used for the ViT models. thanks!

**Comment by rwightman** [comment]
@sagadre it was an experiment I decided to run while training the 'base' convnext models as they were reasonly fast to train, hadn't fit into any of the previous vit runs as we were trying to maintain consistency (as much as possible). After the base runs showed promising results I used it for large and xxlarge

https://huggingface.co/laion/CLIP-convnext_base_w-laion2B-s13B-b82K

**Comment by rwightman** [comment]
Interesting was that for all models the extra random-resize-crop range allowed better scaling with resolution, w/ normal training the performance drops off quickly away from the train res (either higher or lower). For the 'aesthetic' laion subset at 320x320 though, the augreg hurt at the base res but still improved results when inferencing at a higher (or lower) resolution than train.
