### ISSUE TITLE
ViT-H-14 version problem

### ISSUE THREAD

**Issue by 2a3b4c** [mlfoundations/open_clip#440]
I found that the textual latent vector obtained by stable diffusion(v2-1-base) is different from the latent obtained by openCLIP(ViT-H-14), but the textual encoder version in SD is same as the version of openCLIP, why does this happen? i guess if there is the newly trained ViT-H-14 version?

**Comment by 2a3b4c** [comment]
The details of stable diffusion(v2-1-base) can be found in https://huggingface.co/stabilityai/stable-diffusion-2-1-base.

**Comment by rwightman** [comment]
pretty sure SD skips final projection and possibly last layer as well https://github.com/Stability-AI/stablediffusion/blob/06b5b4011591c613b5a51bb3accb3f2e075a12d1/ldm/modules/encoders/modules.py#L176
