### ISSUE TITLE
Error when training in DataParallel model.

### ISSUE THREAD

**Issue by wenlinyao** [mlfoundations/open_clip#45]
**Hi, after updating to your most recent code, I got an error when training in single machine (8 GPUs) in DataParrallel model. I simply changed the flag args.dp = True and got the following error message:**

miniconda3/envs/env37_amp/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:64: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

2022-03-18,06:20:51 | INFO | Start epoch 0
Traceback (most recent call last):
  File "CLIP_model/training/main.py", line 304, in <module>
    main()
  File "CLIP_model/training/main.py", line 243, in main
    train_one_epoch(model, data, epoch, optimizer, scaler, scheduler, args, writer)
  File "CLIP_model/training/train.py", line 149, in train_one_epoch
    total_loss = loss(image_features, text_features, logit_scale)
  File "miniconda3/envs/env37_amp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "CLIP_model/training/train.py", line 97, in forward
    logits_per_image = logit_scale * image_features @ text_features.T
RuntimeError: The size of tensor a (8) must match the size of tensor b (1024) at non-singleton dimension 1

**Code works good when turning args.dp = False and training on a single GPU. 
Thanks!**

**Comment by rwightman** [comment]
FYI @mitchellnw in the code from merge, I left some DP code around, but didn't test it and was planning to remove entirely. I don't see the point in maintaining DP as it's all around worse performance than DDP even on a single node...

**Comment by wenlinyao** [comment]
Thanks for replying! 
Is it possible to provide full instruction on how to install all required environments and how to run DDP (including single-node multi-GPUs and multi-nodes multi-GPUs)? A few example commands would also be very helpful! @rwightman

**Comment by rwightman** [comment]
@wenlinyao on current versions of PyTorch (1.10/1.11) it is really easy w/ torchrun. Older versions you can look up use of the distributed launcher `python3 -m torch.distributed.launch --nproc_per_node=$NUM_PROC script.py args`

An example command line from some recent CC12M training I was doing (4 V100 32GB GPU), launched from the src/ folder...

`torchrun --nproc_per_node 4 -m training.main --train-data '/data/n/download/cc12m/cc12m-train-{0000..2175}.tar' --dataset-type webdataset --batch-size 320 --precision amp --workers 4 --imagenet-val /raid/imagenet/validation/ --gather-with-grad`

**Comment by rwightman** [comment]
Too be clear, no extra components are needed aside from torch, torchrun should be in the path already for a standard conda install (and likely pip, but haven't tested) of pytorch

**Comment by wenlinyao** [comment]
@rwightman After adding `parser.add_argument("--local_rank", type=int, default=0)` to params.py "torch.distributed.launch" is running now. ;)
But I just noticed another problem happened: the running hangs forever at the end of training. (looks like it is due to the synchronization problem?)

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/26070258/159773853-18887558-1d39-47e3-a493-0425faf94959.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/26070258/159774237-45700f0b-df43-48de-98c5-d10754a29aba.png">

I further notice this problem occurs when I pass "data_1/000{00..08}.tar" (9 files) as the training data. The problem won't occur when I pass "data_1/000{00..07}.tar" (8 files) as the training data. I suspect that it is due to dataloader shards distribution problem. 
If "{0000..2175}.tar" in your case works, maybe this problem will disappear after I pass enough ".tar" files?
Thanks!

**Comment by rwightman** [comment]
@wenlinyao using local_rank and the torch.distributed.launch is the 'old' way, but works and I still use it for timm defaults

Yes, you need more shards, shards are distributed across all of the nodes, I would say at bare minimum you probably want at least 2 shards per process (GPU) in distributed setup ... but ideally you shard the dataset with more.

**Comment by wenlinyao** [comment]
@rwightman I see, thanks for your answers!
