### ISSUE TITLE
Correct interpretation of version decoratives

### ISSUE THREAD

**Issue by vinayprabhu** [mlfoundations/open_clip#454]
Is there an official doc for understanding the precise interpretation of the  version decorative strings used here : 
  'laion400m_e31', 'laion400m_e32' implies 'Dataset after 31/32 epochs I suppose. But unsure what the 'epoch' precisely entails.
Similarly, I am totally lost on these:
 ('ViT-B-16', 'laion2b_s34b_b88k'),
 ('ViT-L-14', 'laion2b_s32b_b82k'),
 ('ViT-H-14', 'laion2b_s32b_b79k'),
 ('ViT-g-14', 'laion2b_s12b_b42k'),
 ('ViT-bigG-14', 'laion2b_s39b_b160k'),
 ('roberta-ViT-B-32', 'laion2b_s12b_b32k'),
 ('xlm-roberta-base-ViT-B-32', 'laion5b_s13b_b90k'),
 ('xlm-roberta-large-ViT-H-14', 'frozen_laion5b_s13b_b90k'),
 ('convnext_base', 'laion400m_s13b_b51k'),
 ('convnext_base_w', 'laion2b_s13b_b82k'),
 ('convnext_base_w', 'laion2b_s13b_b82k_augreg'),
 ('convnext_base_w', 'laion_aesthetic_s13b_b82k'),
 ('convnext_base_w_320', 'laion_aesthetic_s13b_b82k'),
 ('convnext_base_w_320', 'laion_aesthetic_s13b_b82k_augreg'),
 ('convnext_large_d', 'laion2b_s26b_b102k_augreg')
 
 Any pointers would be much appreciated!

**Comment by mitchellnw** [comment]
yes e31 and e32 are epoch 31 and 32, where an epoch = pass through the dataset

laion400m, laion2b, and laion_aesthetic are different datasets

ViT-{type} are different types of vision transformers and convnext_{type} are different types of convnexts

s13b means 13b samples seen

augreg is a type of augmentation

b102k is batch size 102k

let me know if there are any other questions

**Comment by vinayprabhu** [comment]
Ah, I see!
Thank you so very much for the reply 🤗 

Just to re-confirm, these strings such as `e31, s13b, b82k, augreg` refer to the model training part and not dataset variants per say, correct?

If so, can we suggest a slightly better and consistent naming hygiene or protocol :) ?
Ex:
LAION_DS_ET_SS_BS_AM
where: 
- DS: Dataset version
- ET: Epochs trained
- SS:  Samples seen 
- BS: Batch-size
- AM: Augmentation method

Lastly, is there any reference to the _whyness_ of these numbers (I am assuming that these were just the coincidental stats of the checkpointed model when the _training-job_ was killed).

Thanks once again :)

**Comment by mitchellnw** [comment]
There is not really a whyness, its more that we are always trying to deliver the best models for the community based on gpu availability etc and also there are many of us.

These are completed jobs with the exception of the e31 which is the second-last epoch which performed better. We moved away from epoch after laion400m because then an epoch was just to big, so we moved to samples seen. Batch size is chosen based on gpu availability etc.

**Comment by vinayprabhu** [comment]
Oh wow. These are very interesting insights! Thanks for patiently addressing the queries. Adding this to the README would be so very useful. 
Context: I am running a few studies where the performance precipitously falls when I switch the model from  the 400M variant to the 2B variants and wanted to see how much of this behavior can be attributed to dataset scaling alone and how much of this might be on account of batch_size variations.
Please let me know if I you have an official citation for these insights.
And thanks once again

**Comment by mitchellnw** [comment]
no problem. The repository has a citation at the bottom of the readme you can use. I would expect that the 2B variants perform better, at least those perform better on ImageNet zero-shot.
