### ISSUE TITLE
OpenCLIP Image Towers in JAX/Flax

### ISSUE THREAD

**Issue by BobMcDear** [mlfoundations/open_clip#459]
Hello,

I am the developer of [flaim](https://github.com/BobMcDear/flaim), a library of pre-trained vision backbones for Flax - think a small subset of timm for the Flax ecosystem. Most of the image towers released in this repository are included in flaim, and I will be adding more (ImageNet fine-tunes as well) in the near future. I reckoned a Flax port of these models might of use to the community but didn't know where to share it, so I opened an issue here - please let me know if this is not the appropriate place, and I would gladly move my announcement elsewhere.

As a side note, as there plans for an end-to-end implementation of OpenCLIP in JAX? JAX offers a few distinct advantages, such as its speed and more native support of large-scale training (especially on TPUs), that render it an attractive potential infrastructure for OpenCLIP.

Thank you for all your great work and contributions to open source.

**Comment by mitchellnw** [comment]
Closing because it duplicates https://github.com/mlfoundations/open_clip/issues/21 . This is a great idea if you or anyone else is interested!
