### ISSUE TITLE
error  with --openai_pretrained

### ISSUE THREAD

**Issue by will-wiki** [mlfoundations/open_clip#46]
hello, I face the problem "TypeError: __init__() takes 4 positional arguments but 11 were given" when calling the  "build_model" function

    if args.openai_pretrained:
      model, preprocess_train, preprocess_val = load(
          args.model,
          device=args.device,
          jit=False,
          is_train=True)
      if args.precision == "amp" or args.precision == "fp32":
          model = model.float()

    def build_model(state_dict: dict):
        vit = "visual.proj" in state_dict
        if vit:
            vision_width = state_dict["visual.conv1.weight"].shape[0]
            vision_layers = len(
                [k for k in state_dict.keys() if k.startswith("visual.") and k.endswith(".attn.in_proj_weight")])
            vision_patch_size = state_dict["visual.conv1.weight"].shape[-1]
            grid_size = round((state_dict["visual.positional_embedding"].shape[0] - 1) ** 0.5)
            image_size = vision_patch_size * grid_size
        else:
            counts: list = [
                len(set(k.split(".")[2] for k in state_dict if k.startswith(f"visual.layer{b}"))) for b in [1, 2, 3, 4]]
            vision_layers = tuple(counts)
            vision_width = state_dict["visual.layer1.0.conv1.weight"].shape[0]
            output_width = round((state_dict["visual.attnpool.positional_embedding"].shape[0] - 1) ** 0.5)
            vision_patch_size = None
            assert output_width ** 2 + 1 == state_dict["visual.attnpool.positional_embedding"].shape[0]
            image_size = output_width * 32
    
        embed_dim = state_dict["text_projection"].shape[1]
        context_length = state_dict["positional_embedding"].shape[0]
        vocab_size = state_dict["token_embedding.weight"].shape[0]
        transformer_width = state_dict["ln_final.weight"].shape[0]
        transformer_heads = transformer_width // 64
        transformer_layers = len(set(k.split(".")[2] for k in state_dict if k.startswith(f"transformer.resblocks")))
    
        model = CLIP(
            embed_dim,
            image_size, vision_layers, vision_width, vision_patch_size,
            context_length, vocab_size, transformer_width, transformer_heads, transformer_layers
        )
    
        for key in ["input_resolution", "context_length", "vocab_size"]:
            if key in state_dict:
                del state_dict[key]
    
        convert_weights_to_fp16(model)
        model.load_state_dict(state_dict)
        return model.eval()

Error caused by the following code。

      model = CLIP(
          embed_dim,
          image_size, vision_layers, vision_width, vision_patch_size,
          context_length, vocab_size, transformer_width, transformer_heads, transformer_layers
      )

I see that you implement the CLIP model __init__ function with only four arguments。Did I get the wrong version?

    class CLIP(nn.Module):
        def __init__(
                self,
                embed_dim: int,
                vision_cfg: CLIPVisionCfg,
                text_cfg: CLIPTextCfg,
        ):

**Comment by will-wiki** [comment]
have anyone can help

**Comment by mitchellnw** [comment]
If you want to use `--openai-pretrained` you may have to revert back to this state of the code: https://github.com/mlfoundations/open_clip/tree/57b3e8ea6ad6bfc2974203945f8fd577e0659468

**Comment by rwightman** [comment]
@mitchellnw @will-wiki fixed with PR #47
