### ISSUE TITLE
Bottleneck while training with multi gpus

### ISSUE THREAD

**Issue by tungdq212** [mlfoundations/open_clip#481]
While training with multi gpus, sometimes 1 gpu sometime use 100% its ult while others is waiting with 0%.
![image](https://user-images.githubusercontent.com/104067740/230300254-7eb2990e-a7b4-4383-92cf-8943eb08fc52.png)

Here is my training command   
```
#!/bin/bash
CUDA_VISIBLE_DEVICES='0,1,2' \
torchrun --nnodes=1 --nproc_per_node=3 --master_addr=localhost --master_port=2120 \
    -m training.main \
    --save-frequency 100 \
    --save-most-recent \
    --zeroshot-frequency 0 \
    --report-to tensorboard \
    --train-data="train.csv" \
    --val-data="val.csv" \
    --csv-img-key item_id \
    --csv-caption-key caption \
    --img-root /mnt/md0/data/images/images/images \
    --warmup 10000 \
    --batch-size=256 \
    --lr=1e-4 \
    --wd=0.1 \
    --epochs=10 \
    --workers=32 \
    --model "ViT-B-32" \
    --csv-separator "," \
    --local-loss \
    --gather-with-grad \
    --name "test5" \
    # --accum-freq 2 \
```

Is this my own problem or anyone else? Can I fix it?

**Comment by HarmanDotpy** [comment]
Not particular suggestion for this repo, but it's likely that one of your gpus is waiting for other gpu's for eg for syncing of data. 
Are you using NCCL backend? if so then you can use 
`export NCCL_ASYNC_ERROR_HANDLING=1`
before running the job. this would not let the job hang forever and it will terminate it after ~30 mins (you can configure this time as well in init function of pytorch ddp). Using this, you may get some information as to which node got stuck and for what reason.

maybe also see 
https://github.com/Lightning-AI/lightning/issues/11242

and my comment about join context manager to make sure all ranks process same number of batches
https://github.com/Lightning-AI/lightning/issues/11242#issuecomment-1413513906

Note that this is not specific advice for this repo, but I think your problem might be similar to the above

**Comment by rwightman** [comment]
@tungdq212 I for one have only tested the webdataset datasets in multi-gpu settings (and on a local 3x GPU machine there has been no issue with cc3m/12m tests in that scenario), possible that as per @HarmanDotpy , there is an issue where batch output differs across processes in multi-gpu + csv dataset.
