### ISSUE TITLE
how to load checkpoints?

### ISSUE THREAD

**Issue by Magiccircuit** [mlfoundations/open_clip#492]
I have trained the clip based on this codebase, and I want to load the trained checkpoint to the original clip model by 
`import CLIP.clip as clip
model, preprocess = clip.load("checkpoints/best_model.pt", device=device, jit=False)`
how can to do it?

**Comment by rwightman** [comment]
@Magiccircuit not sure what lib you're using but doesn' lool like this one, this is OpenCLIP

Basic usage as per README to load a pretrained model https://github.com/mlfoundations/open_clip#usage

To load a local checkpoint you can change the `pretrained=` arg to point to a checkpoint path on your local machine. You can also create the model like in the example without a pretrained arg and to a normal torch.load().
