### ISSUE TITLE
Add ROOT to files written in gather_cc 

### ISSUE THREAD

**Issue by Ascn89** [mlfoundations/open_clip#5]
Hi again,

it would make sense to append `ROOT` to the filepath in the csv-file? Because after running `gather_cc.py` the files are in the folder `cc_data` (eg. `cc_data/val/00/0123.jpg`), but the path in the csv-file is only `val/00/0123.jpg`.

BR Andreas

**Comment by carlini** [comment]
Yes, thanks for noticing this as well. (I had symlinked `train` to `cc_data/train` and similarly for val so didn't notice this.)

**Comment by carlini** [comment]
Should be fixed in 8838feb8d2488b3215c63d0c6b4fedd682f72cfa. Hopefully this is the last issue with the data setup.

**Comment by Ascn89** [comment]
Great for the nearly immediate fix!
It trains now perfectly fine and i am getting the same results as you get. Thanks a lot :)
