### ISSUE TITLE
Confirm about license of model weights

### ISSUE THREAD

**Issue by metalwhale** [mlfoundations/open_clip#503]
Thank for the amazing work!

I saw this mention in the model card of [`laion/CLIP-ViT-H-14-laion2B-s32B-b79K`](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K#out-of-scope-use) pre-trained weights:
> Out-of-Scope Use
> As per the OpenAI models,
> Any deployed use case of the model - whether commercial or not - is currently out of scope.

I have two questions:
- Why do OpenCLIP model weights (not only the above one but also [other pre-trained weights](https://huggingface.co/models?library=open_clip)) have the word "OpenAI models" mentioned in their model cards?
- Is it ok to use these pre-trained models for commercial use? The answer is "yes" in this related issue: #177, but since there are some restrictions mentioned in the model card as I quoted above, I want to check if I'm missing anything.

**Comment by rwightman** [comment]
@metalwhale 'as per' means like the OpenAI models, it's acknowledging that the text of recommendations are based on OpenAI model cards.

No restrictive licensing has been added to the model weights. Take model card as a strong recommendation / warning. The dataset is essentially a snapshot of image - alt-text pairs on the internet at a point in time, an image web search with 'safe search' turned off in some respects. There is a lot of crap in the dataset, there is problematic content in the dataset, one needs to make themselves very familiar with all of the potential issues before considering to deploy hence the text in the model card.

**Comment by metalwhale** [comment]
@rwightman Thank you so much for the detailed explanation. Glad to hear that.
