### ISSUE TITLE
Information about BiomedCLIP-PubMedBERT config

### ISSUE THREAD

**Issue by chinmay5** [mlfoundations/open_clip#505]
I saw that a pull request had been made for BioMedCLIP model. I can also see that it has been merged. However, if I try to load the model using 
`model, _, preprocess_val = open_clip.create_model_and_transforms("BiomedCLIP-PubMedBERT_256-vit_base_patch16_224")`

I get an error

`RuntimeError: Model config for BiomedCLIP-PubMedBERT_256-vit_base_patch16_224 not found.`

On a related note, I can see that the model is available on Huggingface pretrained checkpoints. However, it seems that when these models are converted to the huggingface format, some more wrappers are created. Is it possible to do the reverse i.e. download the huggingface CLIP model weights and convert it to OpenCLIP?

Thanks.

**Comment by rwightman** [comment]
@chinmay5  you can use it via the hub, https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224 ... se example notebook, using `hf-hub:/repoid` lets you load models directly from the hub without them being explicitly added to OpenCLIP, so long as the underlying model config is supported (which was related to the additions here to make sure the Bert HF config mapping worked).

**Comment by usuyama** [comment]
@chinmay5  Thank you for checking out BiomedCLIP :)

**Comment by PIPIWTUES** [comment]
> @chinmay5 you can use it via the hub, https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224 ... see their example notebook, using `hf-hub:/repoid` lets you load models directly from the hub without them being explicitly added to OpenCLIP, so long as the underlying model config is supported (which was related to the additions here to make sure the Bert HF config mapping worked).

Hi, the server network I use is unstable, so I downloaded it in advance and transferred it to ~/.cache/huggingface/hub/models--microsoft--BiomedCLIP-PubMedBERT_256-vit_base_patch16_224, when I execute **model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')** again, the code still reports an error **ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.**, do you have any suggestions for my issue, thank a lot

**Comment by usuyama** [comment]
Hmm, you should be able to load directly from local disk too. Can you try specifying your local path?
