### ISSUE TITLE
[Q] Minimum GPU Ram requirements for inference on models?

### ISSUE THREAD

**Issue by NightMachinery** [mlfoundations/open_clip#509]
What minimum GPU ram do I need for inference on each model, e.g., `ViT-G/14`?

I couldn't find 8-bit inference guides using pretrained weights. Is this possible? What would be the RAM requirements then?

**Comment by mitchellnw** [comment]
I don't think we know the exact amount of GPU RAM required, but you can follow this tutorial for 8-bit inference https://github.com/mlfoundations/open_clip/blob/main/tutorials/int8_tutorial.ipynb

Concretely, your going to want to do something like the following (note I didn't actually check this code, just copied from the tutorial so there may be a typo, please double check tutorial if it doesn't work)

```
import open_clip
import bitsandbytes as bnb

model, _, preprocess = open_clip.create_model_and_transforms('ViT-H-14', pretrained='laion2b_s32b_b79k')
int8_linear_layer = bnb.nn.triton_based_modules.SwitchBackLinear
int8_model = open_clip.utils.replace_linear(model, int8_linear_layer, include_modules=['c_fc', 'c_proj']).cuda()
int8_model.eval()

from open_clip.utils import convert_int8_model_to_inference_mode
convert_int8_model_to_inference_mode(int8_model)

# Now you can do a forward pass with the model...
```
