### ISSUE TITLE
Issue with running Multilingual CLIP properly

### ISSUE THREAD

**Issue by Hritikbansal** [mlfoundations/open_clip#514]
Hi @rom1504 ,

I was trying to work with  ('xlm-roberta-base-ViT-B-32', 'laion5b_s13b_b90k') and ('xlm-roberta-large-ViT-H-14', 'frozen_laion5b_s13b_b90k') for my usecase, and as a sanity check was evaluating them on ImageNet-1K. 

With the same personal setup, I am getting ~60% for  ('ViT-B-32', 'laion400m_e31') on ImageNet-1K but I get 0.1% for both the MCLIPs.

I am loading all the models using the following command, everything stays the same.

`
model, _, preprocess = open_clip.create_model_and_transforms('xlm-roberta-base-ViT-B-32', pretrained='laion5b_s13b_b90k') #Gives 0.1% on ImageNet-1K En
`
gives me this warning: 

```
Some weights of the model checkpoint at xlm-roberta-large were not used when initializing XLMRobertaModel: ['lm_head.dense.bias', 'roberta.pooler.dense.weight', 'lm_head.bias', 'roberta.pooler.dense.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing XLMRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```

but the following command does not give me any warning:

`
model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-32', pretrained='laion400m_e31') #Gives 60% on ImageNet-1K En
`

Can you let me know if there is anything else that needs to change while running the multilingual CLIPs here?

**Comment by rom1504** [comment]
You need to use the get_tokenizer function then use it, see readme

**Comment by Hritikbansal** [comment]
Thank you, makes sense to me!
