### ISSUE TITLE
Could using open_clip pretrained model with transformers package?

### ISSUE THREAD

**Issue by mrluin** [mlfoundations/open_clip#524]
Hello,

Could I use open_clip pretrained model with `transformers`, like following:

```
from transformers import CLIPTextModel, CLIPTokenizer, CLIPVisionModel

tokenizer = CLIPTokenizer.from_pretrained("local_path_of_open_clip")
text_encoder = CLIPTextModel.from_pretrained("local_path_of_open_clip")
image_encoder = CLIPVisionModel.from_pretrained("local_path_open_clip")
```
Though it did not raise errors, but i am not sure if the models have the same architecture.

**Comment by mrluin** [comment]
I tried using pretrained model of `open_clip` with `transformers` pkg, It seems that `from_pretrained` can adaptively recognize the config and model checkpoint.

**Comment by GenoburyUkawa** [comment]
I want to ask if 'local_path_of_open_clip' refers to the locally fine-tuned pt model
