### ISSUE TITLE
Table in README

### ISSUE THREAD

**Issue by SimJeg** [mlfoundations/open_clip#525]
Hi, maybe it would be nicer to include a table instead of a list in the README ? Table below generated by GPT4 (need for verification) with the prompt : 

`
Create a markdown table with columns (Model Type, Dataset, Image Size, ImageNet-1k Zero-shot Top-1 Accuracy and Comment) for the following list. When the image size is not known, use 224x224.
`

| Model Type       | Dataset    | Image Size | ImageNet-1k Zero-shot Top-1 Accuracy | Comment                                                 |
|------------------|------------|------------|---------------------------------------|---------------------------------------------------------|
| ViT-B/32         | LAION-400M | 224x224    | 62.9%                                 | Comparable to OpenAI's 63.2%                            |
| ViT-B/32         | LAION-2B   | 224x224    | 66.6%                                 |                                                         |
| ViT-B/16         | LAION-400M | 224x224    | 67.1%                                 | Lower than OpenAI's 68.3% (as measured here, 68.6% in paper)|
| ViT-B/16+        | LAION-400M | 240x240    | 69.2%                                 | ~50% more FLOPS than B/16 224x224                       |
| ViT-B/16         | LAION-2B   | 224x224    | 70.2%                                 |                                                         |
| ViT-L/14         | LAION-400M | 224x224    | 72.77%                                | Vs OpenAI's 75.5% (as measured here, 75.3% in paper)    |
| ViT-L/14         | LAION-2B   | 224x224    | 75.3%                                 | Vs OpenAI's 75.5% (as measured here, 75.3% in paper)    |
| ViT-L/14         | DataComp-1B| 224x224    | 79.2%                                 | Best ViT-L/14, trained with a 13B samples seen schedule |
| CoCa ViT-L/14    | LAION-2B   | 224x224    | 75.5%                                 | Vs. CLIP ViT-L/14 73.1% (on the same dataset and samples seen)|
| ViT-H/14         | LAION-2B   | 224x224    | 78.0%                                 |                                                         |
| ViT-g/14         | LAION-2B   | 224x224    | 76.6%                                 | Reduced 12B samples seen schedule, same as 400M models  |
| ViT-g/14         | LAION-2B   | 224x224    | 78.5%                                 | Full 34B samples seen schedule                          |
| ViT-G/14         | LAION-2B   | 224x224    | 80.1%                                 | Best in1k zero-shot for released, open-source weights   |
| ConvNext-Base    | LAION-400M | 224x224    | 66.3%                                 |                                                         |
| ConvNext-Base (W)| LAION-2B   | 256x256    | 70.8%                                 |                                                         |
| ConvNext-Base (W)| LAION-2B   | 256x256    | 71.5%                                 | With augreg (extra augmentation + regularization)       |
| ConvNext-Base (W)| LAION-A    | 256x256    | 71.0%                                 | 900M sample aesthetic subset of 2B                      |
| ConvNext-Base (W)| LAION-A    | 320x320    | 71.7%                                 | Eval at 384x384 is 71.0%                                 |
| ConvNext-Base (W)| LAION-A    | 320x320    | 71.3%                                 | With augreg, eval at 384x384 is 72.2%                    |
| ConvNext-Large (D)| LAION-2B  | 256x256    | 75.9%                                 | With augreg                                              |
| ConvNext-Large (D)| LAION-2B  | 320x320    | 76.6%                                 | Fine-tune of 256x256 weights for ~2.5B more samples      |
| ConvNext-Large (D)| LAION-2B  | 320x320    | 76.9%                                 | Soup of 3 fine-tunes of 256x256 weights                  |
| ConvNext-XXLarge |            | 256x256    | 79.1%                                 | Original run                                             |
| ConvNext-XXLarge |            | 256x256    | 79.3%                                 | Rewind of last 10%                                       |
| ConvNext-XXLarge |            | 256x256    | 79.4%                                 | Soup of original + rewind                                |

**Comment by jn2clark** [comment]
In case anyone is interested, I ran a benchmark as well and have the results here
https://docs.google.com/spreadsheets/d/1ftHKf4MovnAyKhGyi05e4DPAumZSIBflE_yuQRsuFIA/edit?usp=sharing
I will upload the code to reproduce as well
