### ISSUE TITLE
Load from local path

### ISSUE THREAD

**Issue by mrluin** [mlfoundations/open_clip#528]
Hello,

How can I loca open_clip pretrained model from local dir, since I should run model on an offline machine.

I tried:
```
model, _, _ = open_clip.create_model_and_transforms("ViT-H-14", pretrained=local_dir)
``` 
The error told me that I cannot pass a directory, how can i fix it? Thanks.

**Comment by gabrielilharco** [comment]
Hi @mrluin, have you tried passing in the path to the checkpoint instead of the folder? E.g. something like `local_dir/checkpoint.pt`

**Comment by mrluin** [comment]
Thanks for your reply @gabrielilharco ,

I use the model from hugging face (https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K), i'm not sure which file should i use in `.create_model_and_transforms()`, so i though it could recognize it automatically and i pass the path to the checkpoint directory at first. :D

**Comment by gabrielilharco** [comment]
For that model, you can use `open_clip.create_model_and_transforms('ViT-H-14', pretrained='laion2b_s32b_b79k')`, let me know if that works for you

**Comment by mrluin** [comment]
Thanks. But i'm using an offline machine, could I directly pass `laion2b_s32b_b79k` to pretrained arg?

**Comment by Xuantho78** [comment]
🌹

**Comment by rwightman** [comment]
you can also download the .pt / .bin file manually on a machine with internet access and pass the path to the file as the pretrained arg ... ie `--pretrained /path/to/open_clip_model.bin`

**Comment by Xuantho78** [comment]
Tôi chán cuộc sống này quá rồi . Gặp một lũ lừa đảo lợi dụng

**Comment by mrluin** [comment]
> you can also download the .pt / .bin file manually on a machine with internet access and pass the path to the file as the pretrained arg ... ie `--pretrained /path/to/open_clip_model.bin`

@rwightman @gabrielilharco , thanks for your help. I download checkpoint from hungging face and only pass `open_clip_pytorch_model.bin` to `pretrained` and that works. 

Another question: there are many other config files in checkpoint folder downloaded from hugging face (e.g. open_clip_config.json, preprocessor_config.json, tokenzier.json), are these files useful or will they be read automatically by only using `--pretrained /path/to/open_clip_model.bin`?

**Comment by mrluin** [comment]
Following, 

I checked source code of `create_model`: when creating open_clip model, it gives some log, such as "loaded {model_name} model config." But when i run `model, _, _ = open_clip.create_model_and_transforms("ViT-H-14", pretrained=/path/to/open_clip_model.bin)`, it didn't raise error and print any feedback. I don't know if the model is created and the checkpoint is loaded sucessfully.

**Comment by rwightman** [comment]
@mrluin if you pass in a checkpoint file via that arg and the keys don't match or it can't load for some reason, it would error out. This approach would work for any models that use the builtin or timm vision towers and the builtin text towers w/ default tokenizer, however, it would fail to load a model with a HF text tower and a HF based tokenizer, that would require caching the tokenizer files in huggingface cache as we have no path to loading that manually right now...

**Comment by mrluin** [comment]
@rwightman Thanks for your help.

I finally use the open-clip checkpoint files from huggingface, and since I want to seperately define CLIP image encoder, text encoder and tokenzier, I tried using `CLIPVisionModel`, `CLIPTextModel`, `CLIPTokenizer` with `.from_pretrained(/path/to/open_clip_model_dir)`.

**Comment by Xuantho78** [comment]
OK

**Comment by HanGuangXin** [comment]
> 

@mrluin Faced with the same error. Have you resolve it? Or any hints please @rwightman?

**Comment by mrluin** [comment]
@HanGuangXin , Just using `transformers.CLIPVisionModel` with open-clip ckpt downloaded from huggingface, like: 
```
image_encoder = CLIPVisionModel.from_pretrained("./CLIP-ViT-H-14-laion2B-s32B-b79K")
```

**Comment by CoinCheung** [comment]
@rwightman @gabrielilharco 
Hi, I got to find that VIT model in this [repo](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main) saves checkpoint with format like this: 
![image](https://github.com/user-attachments/assets/fa96a65d-cbcd-4960-9800-a2fec1fe68fd)

The checkpoint is splitted into 2 parts, how could I load this model locally?
