### ISSUE TITLE
Models described in the README not present on HuggingFace Hub

### ISSUE THREAD

**Issue by cal58** [mlfoundations/open_clip#529]
Specifically, the models trained on LAION-400M are not present.
It would be great to see all the models listed in the top of the README present on the HuggingFace hub.
Ideally the README would list the specific HF model ID for each model too.

The weights for some of these can be found [at this release](https://github.com/mlfoundations/open_clip/releases/tag/v0.2-weights), although this is missing (at least) the results from ViT-g/14 on LAION-2B with fewer samples seen during training.

**Comment by mitchellnw** [comment]
Hello, this may be helpful for locating additional model checkpoints https://github.com/LAION-AI/scaling-laws-openclip

If a model is available via `open_clip.list_pretrained()` then it can be loaded even if it's not on the HF hub -- we only started using HF hub for the larger models

**Comment by rwightman** [comment]
This is the source of truth re what is and isn't on the HF Hub for models available via pretrained arg in the OpenCLIP library: https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/pretrained.py

It's some work to add the older models, verify they were put up correctly, add the model cards, etc so doubt that'll happen in any near time-frame. They all work the same via OpenCLIP API and they're all superseded by better laion2b or datacomp models so I don't see the urgency. Is there a speccific reason why this is needed aside from consistency being nice? :)

NOTE: it's also possible for anyone to push a model to the Hub and use without it being added to pretrained by using hf-hub prefix in the name...

ex:
```
model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')
tokenizer = open_clip.get_tokenizer('hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224')
```

**Comment by cal58** [comment]
Thanks both - the scaling law repository answers my questions on how to easily get CLIP variants.
