### ISSUE TITLE
Convnext not found

### ISSUE THREAD

**Issue by royg27** [mlfoundations/open_clip#539]
Hello,

I am trying to use the base convnext (CLIP-convnext_base-laion400M-s13B-b51K), but it fails with the following error:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/laion/CLIP-convnext_base-laion400M-s13B-b51K/resolve/main/open_clip_config.json`

Is there an updated URL for this model?

**Comment by rwightman** [comment]
@royg27 guess that one fell through the cracks re getting it online, the performance of those weights is pretty unspectacular vs the laion2B ones, do you need it for any particular reason? I might just remove the entry...

**Comment by royg27** [comment]
No, I accidentally tried to load these weights (instead of the 2B ones) and encountered this bug so I reported it.
