### ISSUE TITLE
Pretrained weights not found

### ISSUE THREAD

**Issue by VitaLemonTea1** [mlfoundations/open_clip#544]
Hi!

I am trying to use the openclip to recurence another project, but it fails with the following error:

RuntimeError: Pretrained weights (/data/open_clip/open_clip_pytorch_model.bin) not found for model ViT-H-14.Available pretrained tags (['laion2b_s32b_b79k']

So, how can I solve this problem.

Thanks!

**Comment by mitchellnw** [comment]
Hello, are you calling something like

```
model, _, preprocess = open_clip.create_model_and_transforms('ViT-H-14', pretrained='laion2b_s32b_b79k')
```

**Comment by VitaLemonTea1** [comment]
yes，this part of code is
if engine == "clip":
    print("Loading CLIP...")
    model, preprocess = clip.load("ViT-L/14", device=device)
elif engine == "openclip":
    print("Loading OpenCLIP CLIP...")
    open_clip_path = "/data/open_clip/"
    model_cards = {
        "ViT-B-16": "ViT-B-16_openai.pt",
        "ViT-B-32": "ViT-B-32_openai.pt",
        "ViT-L-14": "ViT-L-14_laion2b_s32b_b82k.pt",
        "ViT-H-14": "open_clip_pytorch_model.bin",
    }
    models = list(model_cards.keys())
    clip_index = 3  # default to use the VIT-H-14
    model, _, preprocess = open_clip.create_model_and_transforms(
        models[clip_index],
        device=device,
        pretrained=os.path.join(open_clip_path, model_cards[models[clip_index]]),
    )
    tokenizer = open_clip.get_tokenizer("/data/openclip_tokenizer", direct_load=True)

**Comment by VitaLemonTea1** [comment]
it seems like I use a wrong path，but I also can‘t find ’open_clip_pytorch_model.bin‘ in my file.
Where can I get this file.
Thanks!

**Comment by nbbb24** [comment]
> it seems like I use a wrong path，but I also can‘t find ’open_clip_pytorch_model.bin‘ in my file. Where can I get this file. Thanks!

download by using https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin

**Comment by CaptainWang98** [comment]
@VitaLemonTea1 hi there, i am playing with Instruct2Act too! Nice to meet you. But I figure out this error: 
`File "/Instruct2Act/engine_robotic.py", line 91, in <module>
    tokenizer = open_clip.get_tokenizer("/data/openclip_tokenizer", direct_load=True)
TypeError: get_tokenizer() got an unexpected keyword argument 'direct_load'`
Do you know why there is a argument 'direct_load'? Thanks~
