### ISSUE TITLE
How to determine train_num_samples?

### ISSUE THREAD

**Issue by samuelstevens** [mlfoundations/open_clip#555]
How do you determine the `train_num_samples` for Laion-2B? For example, this [run](https://wandb.ai/rom1504/open-clip/runs/2xpw65p8/overview?workspace=) uses `train_num_samples = 135646078` (and in fact many runs do that). 

Shouldn't `train_num_samples` be 2170337258? (From `src/training/data.py`)

**Comment by samuelstevens** [comment]
@rom1504 This is your wandb run by the way.

**Comment by rom1504** [comment]
We do sampling with replacement and pick an arbitrary number for the epoch
length. Usually chosen to be about 1h of training time so checkpoints are
done often enough

**Comment by samuelstevens** [comment]
Thanks!
