### ISSUE TITLE
clip_benchmark integration

### ISSUE THREAD

**Issue by usuyama** [mlfoundations/open_clip#557]
I'm wondering if we can automatically run [clip_benchmark](https://github.com/LAION-AI/CLIP_benchmark) to get validation metrics.

Currently, OpenCLIP integrates Imagenet zero-shot, but I'm particularly interested in utilizing other datasets, particularly biomedical datasets.

I came across a comment by @rom1504 mentioning that it's too slow, but I'm curious if it would be feasible to use clip_benchmark for evaluation with smaller datasets.
 
https://github.com/mlfoundations/open_clip/issues/137

**Comment by rwightman** [comment]
I think this can be hacked together with both projects as is but not enough maint manpower to integrate
