### ISSUE TITLE
OpenClip on Apple M1

### ISSUE THREAD

**Issue by shersoni610** [mlfoundations/open_clip#567]
Hello,

Is there a way to run the OpenClip on Apple M1 using "mps" device ?

Thanks

**Comment by EIFY** [comment]
I am working on it (https://github.com/mlfoundations/open_clip/pull/654) but it may take a bit more time to merge. It might not help that much on M1 though...

**Comment by rwightman** [comment]
Fixed, runs fine on my old M1
