### ISSUE TITLE
what's the model architecture to generate text from image?

### ISSUE THREAD

**Issue by ldfandian** [mlfoundations/open_clip#568]
I can't find it in the paper, can someone help answer?

<img width="860" alt="image" src="https://github.com/mlfoundations/open_clip/assets/5018331/622d34c8-0edf-4b46-8da6-a64ae3ed76c6">

**Comment by WalBouss** [comment]
The paper's title is: _CoCa: Contrastive Captioners are Image-Text Foundation Models_.
https://arxiv.org/abs/2205.01917
