### ISSUE TITLE
YFCC-15M pretrained hyperparameters are unclear

### ISSUE THREAD

**Issue by slymane** [mlfoundations/open_clip#570]
Under the README, the hyperparameters used for training YFCC-15M are specified as:

> These models were trained using 8 GPUs and the same hyperparameters described in the "Sample running code" section, with the exception of `lr=5e-4` and `epochs=32`.

However, there is no section named "Sample running code" and the HPs for scripts under "Sample single-process running code" and the multi-node training examples are all different. What are the correct HPs for replicating your YFCC-15M results?

**Comment by mitchellnw** [comment]
The sample running code is

```
python -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to tensorboard \
    --train-data="/path/to/train_data.csv"  \
    --val-data="/path/to/validation_data.csv"  \
    --csv-img-key filepath \
    --csv-caption-key title \
    --imagenet-val=/path/to/imagenet/root/val/ \
    --warmup 10000 \
    --batch-size=128 \
    --lr=1e-3 \
    --wd=0.1 \
    --epochs=30 \
    --workers=8 \
    --model RN50
 ```
