### ISSUE TITLE
Help on strange error:

### ISSUE THREAD

**Issue by shersoni610** [mlfoundations/open_clip#575]
hello,
I am running the following example from the web:

model, _, transform = open_clip.create_model_and_transforms(
  model_name="coca_ViT-L-14",
  pretrained="mscoco_finetuned_laion2B-s13B-b90k"
)
im = Image.open("cat.jpg").convert("RGB")
im = transform(im).unsqueeze(0)
with torch.no_grad():
  generated = model.generate(im)
print(open_clip.decode(generated[0]).split("<end_of_text>")[0].replace("<start_of_text>", ""))

I get the following error:

in _generate_beamsearch
    raise ValueError(
ValueError: Batch dimension of `input_ids` should be 18, but is 6.

what should I do?

Thanks

**Comment by leeesangwon** [comment]
Try num_beam_groups=1

```diff
- generated = model.generate(im)
+ generated = model.generate(im, num_beam_groups=1)
```

I think there is a bug when num_beam_groups != 1

https://github.com/mlfoundations/open_clip/blob/24ddefb37fc4892f6a0c975b732226fe8a9a8613/src/open_clip/coca_model.py#L323

The code should be modified as shown in the link below

https://github.com/huggingface/transformers/blob/e42587f596181396e1c4b63660abf0c736b10dae/src/transformers/generation/beam_search.py#L227

```diff
- batch_size = len(beam_scorer._beam_hyps)
+ batch_size = len(beam_scorer._beam_hyps) // beam_scorer.num_beam_groups
```

**Comment by shersoni610** [comment]
Thank you so much. Greatly appreciate for such a prompt reply.

**Comment by leeesangwon** [comment]
I also had the same issue, so I searched for it a while ago.
It's a brand new bug that occurred after the update to transformers 4.31.0 two days ago. 😂

https://github.com/huggingface/transformers/commit/43479ef98f2d9f1600793922cf022d7d0670a5f8

If you need `num_beam_groups > 1`, try with transformers==4.30.2

**Comment by robgon-art** [comment]
Hi @leeesangwon, using transformers==4.30.2 worked for me, thanks!

https://colab.research.google.com/github/robgon-art/open-clip/blob/main/Create_Captions_with_CoCa_and_OpenCLIP.ipynb

**Comment by shersoni610** [comment]
Hello,. 

A naive question:  What is the impact of num_beam_groups on the quality or speed of the model?

**Comment by robgon-art** [comment]
I haven’t experimented with this. I only used the defaults and they seemed to work fine, albeit a tad slow.

BTW: Did the fix work for you?
