### ISSUE TITLE
when trying xlm-roberta-base-ViT-B-32 with pretrained weights  'laion5b_s13b_b90k', the following error comes in colab.  Could u help?

### ISSUE THREAD

**Issue by chandrabhuma** [mlfoundations/open_clip#576]
Downloading (…)lve/main/config.json: 100%
615/615 [00:00<00:00, 40.5kB/s]
Downloading model.safetensors: 100%
1.12G/1.12G [00:04<00:00, 226MB/s]
Downloading (…)ip_pytorch_model.bin: 100%
1.46G/1.46G [01:21<00:00, 19.8MB/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-6-6a2aeff7b530>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model, _, preprocess = open_clip.create_model_and_transforms('xlm-roberta-base-ViT-B-32', pretrained='laion5b_s13b_b90k')

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   2039 
   2040         if len(error_msgs) > 0:
-> 2041             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                                self.__class__.__name__, "\n\t".join(error_msgs)))
   2043         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for CustomTextCLIP:
	Unexpected key(s) in state_dict: "text.transformer.embeddings.position_ids".

**Comment by tgisaturday** [comment]
Encountered same issue. Seems like there's some change in transformers. Downgrading transformers==4.30.0 fixed the problem.

**Comment by chandrabhuma** [comment]
Thanks a lot. It is working fine.
