### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by Yangr116** [mlfoundations/open_clip#580]
Hi, how could I use the open_clip in an offline environment? My machine can not access to Internet.

**Comment by christuchez** [comment]
Load the model from your local directory using cache_dir

`model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-32',
                                                                                                        pretrained='laion2b_s34b_b79k',
                                                                                                        cache_dir='path_to_my_model')`

**Comment by Yangr116** [comment]
Yes, I used this method, but it still tries to download the model.
I used below code:
```
model, _, _ = open_clip.create_model_and_transforms(
    arch="ViT-H-14",
    pretrained="laion2b_s32b_b79k",
    cache_dir="my_cache"
)
```
Files have below structure in ```my_cache```:
```
my_cache
-- models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K
----open_clip_pytorch_model.bin
----tokenizer.json
...
----vocab.json
```
(I download the source file from huggingface instead of using the method that has a snapshot.)

Can you give me some advices? Many Thanks.

**Comment by Yangr116** [comment]
Solved by setting ```arch```  to ```hf-hub: huggingface_name```, and undating the ```huggingface-hub```.

**Comment by niushixiong** [comment]
how to  set param ？
