### ISSUE TITLE
Training details for convnext_base.laion400m_s13b_b51k and ViT-B-16.laion400m_e31

### ISSUE THREAD

**Issue by kirill-vishniakov** [mlfoundations/open_clip#598]
Hi, 

I have been looking for training details for two models of `convnext_base.laion400m_s13b_b51k` and `ViT-B-16.laion400m_e31` but couldn't find anything. Usually, there is at least a SLURM script on HF Hub available, but for these two models, it's absent. 

I'm interested to know training details for these models, including data aug, optimizers, regularization and etc. Can you please provide these details?

**Comment by rwightman** [comment]
@kirill-vishniakov add this https://github.com/mlfoundations/open_clip/tree/main#slurm + https://github.com/mlfoundations/open_clip/blob/main/docs/PRETRAINED.md#vit-b16-224x224 and you have the B/16 details, that 400m convnext_base was similar (very basic hparams, no extra augs or fiddling with LR/beta2).
