### ISSUE TITLE
`logit_scale` in `CLIP`

### ISSUE THREAD

**Issue by sarahESL** [mlfoundations/open_clip#6]
Thanks for preparing this repo.
I was wondering how is `self.logit_scale = nn.Parameter(torch.ones([]) * np.log(1 / 0.07))`  decided? I mean where is this value `np.log(1 / 0.07))` inspired from?

**Comment by sarahESL** [comment]
Ah! found it in the original CLIP paper! :grimacing:  Sorry for spamming!

**Comment by mitchellnw** [comment]
No worries!
