### ISSUE TITLE
BUG regarding use of LayerNorm

### ISSUE THREAD

**Issue by yonghanyu** [mlfoundations/open_clip#603]
Hi, I might find a potential bug regarding the use of LayerNorm. 

In the file [src/open_clip/transformer.py](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/transformer.py#L612), the input tensor was permutated with sequence length as the first dimension. The permutated tensor was then passed into ResidualAttentionBlock, where the LayerNorm was directly applied to the permutated tensor. 

However, according to pytorch documentation, the input of LayerNorm should have batch first structure.

**Comment by mitchellnw** [comment]
Could be wrong but i believe it only matters what the last dimension is?

**Comment by yonghanyu** [comment]
> Could be wrong but i believe it only matters what the last dimension is?

Thanks for the reply. I double checked the layernorm implementation and you are right!
