### ISSUE TITLE
What is the token limit of these models?

### ISSUE THREAD

**Issue by AyushExel** [mlfoundations/open_clip#604]
The original CLIP model has the token limit of 77 tokens. But in these models I'm able to embed much larger text. Is the model capable of handling larger texts or is it simply ignoring the extra parts? Thanks!

**Comment by gabrielilharco** [comment]
hey @AyushExel. Unfortunately I believe this won't work because the text transformer uses learned positional embeddings with max length of 77.  One possibility would be to fine-tune the model with larger sequence lengths.

**Comment by AyushExel** [comment]
@gabrielilharco yeah this is why I'm confused. Actually, I'm using it to embed sentences of more than 77 tokens and it's working.

**Comment by AyushExel** [comment]
Ahh that's it. Thanks :)
