### ISSUE TITLE
Cannot import name 'CLIP3D' from 'open_clip'

### ISSUE THREAD

**Issue by atelili** [mlfoundations/open_clip#609]
Hello, I might find a problem when importing CLIP3D:
ImportError: cannot import name 'CLIP3D' from 'open_clip'.
Thank you

**Comment by gabrielilharco** [comment]
Hi @atelili, this is not a module form our library. Are you sure your not supposed to import it from somewhere else?

**Comment by atelili** [comment]
Thanks for your quick reply, I'll check it out ^^.
