### ISSUE TITLE
Am I missing something with torch.compile?

### ISSUE THREAD

**Issue by jn2clark** [mlfoundations/open_clip#610]
Hello! I don't see a speed up during training with `torch.compile` - is there something else I am missing? I think I must be doing something wrong.  Does anyone have any numbers they can share if they saw a speed up (if at all)? I tried ViT-L14, 2.0.1/11.8 and nightly '2.1.0.dev20230827+cu121' using 4 A100's (530.41.03). To add though, I patched an older version of open_clip. Maybe I need to upgrade? Thanks!

**Comment by EIFY** [comment]
As a data point, `torch.compile` provides ~15% speedup for me:
```
--model RN50
torch==2.0.1+cu118
Single NVIDIA GeForce RTX 3080 Laptop GPU (525.125.06)
```

**Comment by jn2clark** [comment]
Thanks @EIFY ! Do you have numbers for any of the ViT class models? I will test again on the latest versions.

**Comment by EIFY** [comment]
@jn2clark For `ViT-S-16` it's about 27% speedup for me. Same GPU, PyTorch now updated to `torch==2.1.0`

**Comment by jn2clark** [comment]
Thanks @EIFY ! This is very helpful.
