### ISSUE TITLE
add option to pass revision to create_model_and_transforms 

### ISSUE THREAD

**Issue by david-gang** [mlfoundations/open_clip#611]
The function [create_model_and_transforms](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/factory.py#L290) calls [download_pretrained_from_hf](https://github.com/mlfoundations/open_clip/blob/ab1ae01731885ef2436a40e3c8c147347f18153e/src/open_clip/factory.py#L128C23-L128C50) which has a parameter [revision](https://github.com/mlfoundations/open_clip/blob/ab1ae01731885ef2436a40e3c8c147347f18153e/src/open_clip/pretrained.py#L391). 

Unfortunately there is no option to pass the revision. Can this be added?

This will make the use of the library more deterministic as no newer revisions will be downloaded automatically

**Comment by weiyuwang2021** [comment]
create_model_and_transforms force to upgrade to new revision, it broke my service. Can you add the revision option to the function?

**Comment by rom1504** [comment]
What model broke for you?

**Comment by rwightman** [comment]
there is very little precedent for having old incompatible weights in past revisions on the HF hub (for typical use cases here), we typically try hard to maintain config & state dict key compatibility with old weights. I can't think of any case where there is an 'old' revision of any weights were this would help.
