### ISSUE TITLE
Datacomp runs

### ISSUE THREAD

**Issue by gpucce** [mlfoundations/open_clip#619]
Hi, 

Is there any public wandb report of a clip run on datacomp? Maybe a ViT-B-32?

Thanks!

**Comment by gabrielilharco** [comment]
@afang-story maybe has this?

**Comment by afang-story** [comment]
I don't believe we have a public wandb report of this. Are there specific details you are looking for? I may be able to retrieve the relevant portions.

**Comment by afang-story** [comment]
Looks like I can change some to be public
Here is a sample one:
https://wandb.ai/dogml/datanet/runs/scale128M_clip_threshold_clip_b32_f0.3_sd0/
Medium scale, clip threshold b32 f0.3

**Comment by gpucce** [comment]
I was curious for a b/32 with 13B samples seen smth comparable to the smaller coca run

**Comment by afang-story** [comment]
Sorry we don't have a clean wandb log of that
For now I've created a public wandb project that contains a medium run as a sample - hopefully this is still helpful
https://wandb.ai/dogml/datacomp-public-sample/runs/scale128M_clip_threshold_clip_b32_f0.3_sd0

**Comment by gpucce** [comment]
Hi @afang-story thank you the run report. Can I ask you just to point me to a pair of comparable laion 2b <--> Datacomp runs with same samples seen, if there are any? Thank you so much in advance and if there are none available I will close the issue.

**Comment by afang-story** [comment]
Hello, I couldn't find any clean wandb reports trained on the actual LAION pool, but I moved two large scale runs to the same public project as the above link. One is laion style filtering on our large scale pool, and the other is the equivalent to DC-1B filtering on our large scale pool. Hope this helps!

**Comment by gpucce** [comment]
> Hello, I couldn't find any clean wandb reports trained on the actual LAION pool, but I moved two large scale runs to the same public project as the above link. One is laion style filtering on our large scale pool, and the other is the equivalent to DC-1B filtering on our large scale pool. Hope this helps!

That's beautiful thank you so much!

**Comment by leng-yue** [comment]
Hi, I see a `--scale 1.28B ` in the training commands, what's that used for? Is it equivalent to adjust `epochs` manually?

**Comment by afang-story** [comment]
"1.28B" was the old name for "large" scale

**Comment by leng-yue** [comment]
Thanks
