### ISSUE TITLE
Error loading openai models

### ISSUE THREAD

**Issue by teasgen** [mlfoundations/open_clip#622]
I'm trying to download openai model using [create_model](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/factory.py#L112) from checkpoint containing the state_dict. 
As indicated in [load_openai_model](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/openai.py#L35) script I can supply checkpoint file as model name. Unfortunately, path (model_name) changes in [this line ](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/factory.py#L139) and becomes invalid (e.g path /home/model.pt -> -home-model.pt - invalid path).
To fix this issue I suggest to rewrite line to:
```
if not os.path.isfile(model_name):
    model_name = model_name.replace('/', '-')  # for callers using old naming with / in ViT names
```

**Comment by gabrielilharco** [comment]
Hey @teasgen, your fix should work. I'm not sure exactly where your checkpoint comes from, but have you tried using something like `ViT-B-32` for the model named and `/your/path.to/ckpt.pt` for the `pretrained` arg?

**Comment by teasgen** [comment]
> Hey @teasgen, your fix should work. I'm not sure exactly where your checkpoint comes from, but have you tried using something like `ViT-B-32` for the model named and `/your/path.to/ckpt.pt` for the `pretrained` arg?

Hey, yes, I've tried it, but if I pass pretrained argument which is not "openai" for openai ckpt.pt, it failed during model downloading `AttributeError: 'RecursiveScriptModule' object has no attribute 'items'`. I suppose this is because checkpoint loading for "openai" models and other is different.

I've downloaded it from [pretrained](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/pretrained.py#L158)  file. Of course there is a solution, pass args:
model_name Vit-l-14-336
pretrained openai
cache_dir `/path/to/checkpoint/folder`
But I'd like to use pipeline as described in my previous comment

**Comment by teasgen** [comment]
@gabrielilharco Thanks for your PR, how soon will the updated version be released on pypi?

**Comment by gabrielilharco** [comment]
Hey @teasgen, I was chatting about this with @rwightman and he suggested the following, which doesn't require any code changes.

```
model = open_clip.load_openai_model('/home/model.pt') # you can use a path in the name here w/o it being cleaned
model.to(torch.float32)
torch.save(model.state_dict(), '/home/openclip_model.pt')
```

then to load

```
model, _, preprocess = open_clip.create_model_and_transforms('ViT-B-32', pretrained=' /home/openclip_model.pt', force_quick_gelu=True)
```

Let me know if that works for you!

**Comment by rwightman** [comment]
Just to be clear why I think the suggestion above makes more sense, the `load_openai_model` originated from OpenAI's CLIP codebase, it was integrated with OpenCLIP's factory method to support loading OpenAI models when needed, but via the pretrained model download mechanism.

OpenAI's models were released in a deployment friendly mode, they are stand-alone JIT archives, not state dicts. OpenCLIP models are created from a config, so name is needed for lookup, using a path as a model name would never work. So don't really think it makes sense to start overloading the name for pass through to the openai, doing filesystem checks everytime a model is created, etc. If it's needed to load locally, one can just convert the jit archive to a state dict once as per the code above and then use the pretrained arg with the path...

**Comment by rwightman** [comment]
One last thought on this, without changing the create_model fns to overload the meaning of 'name'

We could change checkpoint loading to auto-convert a jit archive to state dict so that using pretrained with the path of a jit archive would work with a matching model name (but remember to enable QuickGELU).
```
def load_state_dict(checkpoint_path: str, map_location='cpu'):
    checkpoint = torch.load(checkpoint_path, map_location=map_location)
    if isinstance(checkpoint, dict) and 'state_dict' in checkpoint:
        state_dict = checkpoint['state_dict']
    elif isinstance(checkpoint, torch.jit.ScriptModule):
        state_dict = checkpoint.state_dict()
        for key in ["input_resolution", "context_length", "vocab_size"]:
            state_dict.pop(key, None)
    else:
        state_dict = checkpoint
    if next(iter(state_dict.items()))[0].startswith('module'):
        state_dict = {k[7:]: v for k, v in state_dict.items()}
    return state_dict
```

**Comment by teasgen** [comment]
> 

Thank you for your comprehensive answer, I agree with you, that passing model path as model name is a bad idea. My first point was to use create_model_and_transforms for openai models and openCLIP in the same way, and it would be cool if you added auto-converting. Am I right that then it will be possible to download openai models thus: open_clip.create_model_and_transforms('ViT-B-32', pretrained='/home/openai_model.pt', force_quick_gelu=True)?

**Comment by rwightman** [comment]
@teasgen yes if the load_state_dict fn here: https://github.com/mlfoundations/open_clip/blob/79a20ee9e13d612b44bebe1581aa83cf467c281b/src/open_clip/factory.py#L87-L95 was changed to the one above, that would work, I tested for the B/32 and it matched expected results.
