### ISSUE TITLE
Version limit for protobuf

### ISSUE THREAD

**Issue by HAlirezaFatemiH** [mlfoundations/open_clip#623]
Hi.

Is there a reason for having an upper limit on the `protobuf` package version? (protobuf<4)
I'm using poetry and this forces me to downgrade the `protobuf` version.

**Comment by gabrielilharco** [comment]
Hi @HAlirezaFatemiH. Some later versions of protobuf break some models (see https://github.com/mlfoundations/open_clip/issues/246)

**Comment by HAlirezaFatemiH** [comment]
Might this have been fixed with [this](https://github.com/huggingface/transformers/pull/24599) so we can remove the version limit?
