### ISSUE TITLE
ResizeMaxSize does not pad tensor

### ISSUE THREAD

**Issue by nik-ko** [mlfoundations/open_clip#629]
In `ResizeMaxSize` no padding is performed, if no resize is needed:
https://github.com/mlfoundations/open_clip/blob/a4b5bc351ed2e871911fe509d2824fb8e3d63d99/src/open_clip/transform.py#L43C8-L43C8
If `width` or `height` are the same as `self.max_size` no padding is applied and an the output won't have shape `self.max_size * self.max_size`. If `width` or `height` are different from `self.max_size`, the tensor is padded to `self.max_size * self.max_size`
The expected behavior is that resize is not performed when `scale == 1.0` but padding is still necessary if width and height are not the same.

I suppose this is not intended since for preprocessing `image_transform` calls `ResizeMaxSize` and inputs for CLIP are required to have a fixed size, e.g. 224*224.

I replaced the following lines
```
      if scale != 1.0:
              new_size = tuple(round(dim * scale) for dim in (height, width))
              img = F.resize(img, new_size, self.interpolation)
              pad_h = self.max_size - new_size[0]
              pad_w = self.max_size - new_size[1]
              img = F.pad(img, padding=[pad_w//2, pad_h//2, pad_w - pad_w//2, pad_h - pad_h//2], fill=self.fill)
```

with

```
        new_size = tuple(round(dim * scale) for dim in (height, width))
        if scale != 1.0:
            img = F.resize(img, new_size, self.interpolation)
        if not width == height:
            pad_h = self.max_size - new_size[0]
            pad_w = self.max_size - new_size[1]
            img = F.pad(img, padding=[pad_w//2, pad_h//2, pad_w - pad_w//2, pad_h - pad_h//2], fill=self.fill)
```

**Comment by nik-ko** [comment]
I just noticed that the same issue is described in #600

**Comment by rwightman** [comment]
@nik-ko merged the PR, thanks... that transform isn't actively used by default, imagine it would have been fixed sooner if it was.
