### ISSUE TITLE
In what form is custom data organized?

### ISSUE THREAD

**Issue by ShuxunoO** [mlfoundations/open_clip#640]
I am going to finetune CLIP model in my own img-caption pairs，but what form should I handle them？

I have tried the [img2dataset](https://github.com/rom1504/img2dataset) script example，and got an folder named “bench”，the folder structure just like following：

```
--bench
    | --00000
        --00000000.jpg
        --00000000.json
        --00000000.txt
        --00000001.jpg
        --00000002.json
        --00000002.txt
               ……

    | --00001
        --00001000.jpg
        --00001000.json
        --00001000.txt
        --00001001.jpg
        --00001002.json
        --00001002.txt
               ……
```

I can organize my local data in this form。**But** in the  official demo：**[Sample single-process running code]( https://github.com/mlfoundations/open_clip/tree/main#sample-single-process-running-code)** 

```
python -m training.main \
    --save-frequency 1 \
    --zeroshot-frequency 1 \
    --report-to tensorboard \
    --train-data="/path/to/train_data.csv"  \
    --val-data="/path/to/validation_data.csv"  \
    --csv-img-key filepath \
    --csv-caption-key title \
    --imagenet-val=/path/to/imagenet/root/val/ \
    --warmup 10000 \
    --batch-size=128 \
    --lr=1e-3 \
    --wd=0.1 \
    --epochs=30 \
    --workers=8 \
    --model RN50
```
 
` --train-data="/path/to/train_data.csv" `

Where is the “train_data.csv”  comes from？ and how is the content of the csv file organized? 

Can you give me an example? Or is there a script in the repo that converts the data organization form? Thank you very much for helping me!

**Comment by rom1504** [comment]
Prefer using webdataset format

**Comment by EIFY** [comment]
To use `webdataset` format, replace
```
    --train-data="/path/to/train_data.csv"  \
    --csv-img-key filepath \
    --csv-caption-key title \
```
with
```
    --train-data='/data/bench/{00000..00001}.tar' \
    --train-num-samples 2000 \
    --dataset-type webdataset \
```
Change the tar filename range and number of samples for your `bench` dataset. If you have a validation dataset then use it for `--val-data`, otherwise you can skip it for now.
