### ISSUE TITLE
How can I  specify the GPU IDs when training the model？

### ISSUE THREAD

**Issue by ShuxunoO** [mlfoundations/open_clip#643]
When I finetune the clip model， I need to choose which gpus to use，the demo author offers：[Sample single-process running code:](https://github.com/mlfoundations/open_clip#sample-single-process-running-code)  just start from CUDA 0. 

BUT how can I  specify the GPU IDs when training the model？

**Comment by mitchellnw** [comment]
can you use `export CUDA_VISIBLE_DEVICES=<which-gpus-to-use>`

**Comment by ShuxunoO** [comment]
It really work！ Thank you！！！  

But at the same time, I also think it would be better if it could be specified in the parameters. For example:

python -m training.main \
    --save-frequency 1 \
    --report-to tensorboard \
    --model 'ViT-B-32' \
    --device 1,2,4 \
    ……

 I hope you can consider my suggestion.

**Comment by rwightman** [comment]
@ShuxunoO specifying devices via args is not going to happen, each train process now covers one GPU, multi-GPU is done via DDP by launching multiple processes with torchrun or slurm scripts, we are not expanding the scope of the train script to handle launching as it adds a lot of complexity
