### ISSUE TITLE
Inference error "killed"

### ISSUE THREAD

**Issue by GuitarZH** [mlfoundations/open_clip#656]
Thanks for your excellent work and code.
However, I met an error when inference general image dataset, as shown below. 
![image](https://github.com/mlfoundations/open_clip/assets/21530577/6ac06c40-ec5a-4974-b29a-490bf70296ec)

Can you help me? Thanks very much in advance!

**Comment by rwightman** [comment]
@GuitarZH don't think that issue is relevant to this project. You likely exceeded system memory limits and the process got killed.
