### ISSUE TITLE
Proposal: Remove 'Dual PatchNorm' support (input_patchnorm)

### ISSUE THREAD

**Issue by rwightman** [mlfoundations/open_clip#666]
I've been working with the models quite a bit trying to sensibly combine CLIPA and SigLIP support. What became apparent is that having unused bits of extra functionality in the core model codepath is a liability if nobody is actively policing.

As the example, the original impl of global average pooling was a mistake, we never used it here in OpenCLIP, it wasn't really the best option (pooling both class and spatial tokens), but CLIPA did use it in v1, and then picked the 'better' approach in v2. 

The input patch norm for dual patch norm is similar. It adds a non trivial chunk of code in the main forward path that (I don't think) has ever been used, and AFAIK, there is little benefit to it. I've yet to see a convincing arg that the extra input norm is worth it. Haven't seen it propagate to other vit models w/ pretrained weights.

So, I propose to remove it for the sake of maintenance sanity.

Thoughts @gabrielilharco @mitchellnw @mehdidc @rom1504

**Comment by gabrielilharco** [comment]
In general I'm very onboard with keeping the codebase clean and removing unused/unnecessary features. For this specific case, one question I have is why haven't we been using it in the first place. From https://github.com/mlfoundations/open_clip/pull/405#issuecomment-1418322306 it looks like @mitchellnw had some success with it and saw accuracy improvements, shouldn't we be using in our runs?

**Comment by rwightman** [comment]
@gabrielilharco yeah, that was the reason it got merged in the first place ... I tried to replicate in a classificiation context a little later to decide if it made sense to add to timm, I couldn't get any improvement by the end of train. 

That result there was after 20k steps, not sure if it would have held to the end of train. Don't no if anyone has ever done a full train cycle with that...

**Comment by mitchellnw** [comment]
It improved accuracy for B but in later experiments in my setting, the gains mostly went away for L. So removing sounds good to me, sorry I should have tested more at scale initially.
