### ISSUE TITLE
Can not read my Fine-Tuned CoCa from HF

### ISSUE THREAD

**Issue by Msalehi237** [mlfoundations/open_clip#668]
I have fine-tuned CoCa on a new dataset and pushed it to HF using:

`python3 -m open_clip.push_to_hf_hub --model coca_base --pretrained checkpoints/epoch_1.pt  --repo-id Msalehi237/ArtemisCoCa2`

When trying to load it back using open_clip as below I run into an error:

```
model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:Msalehi237/ArtemisCoCa2')
tokenizer = open_clip.get_tokenizer('hf-hub:Msalehi237/ArtemisCoCa2')

TypeError: CustomTextCLIP.__init__() got an unexpected keyword argument 'multimodal_cfg'
```

Any idea what needs to be added here?

Thanks,

**Comment by rwightman** [comment]
heh, I think it's because whoever wrote this check wasn't thinking  far enough ahead.. heh https://github.com/mlfoundations/open_clip/blob/7e2d222fbde1de303724a0d31e83a6f19afa526a/src/open_clip/factory.py#L209 

If lowercase 'coca' is not in the name it won't try to load the coca model, woops!

**Comment by rwightman** [comment]
I think `'multimodal_cfg' in model_cfg` would be more robust as CoCa is the only model right now which accepts that config, could change in the future, but would need a new entry in the config to differentiate, not based on name... PR welcome

**Comment by gpucce** [comment]
@rwightman @Msalehi237 the check is for sure my fault, if you don´t have time I can make the PR

**Comment by Msalehi237** [comment]
Thank you! So, for now, if I just use a lower case 'coca' in the model name it will work, right?

**Comment by Msalehi237** [comment]
And I can do the PR if you guys don't have time @gpucce
