### ISSUE TITLE
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout

### ISSUE THREAD

**Issue by kinredon** [mlfoundations/open_clip#669]
When I use `torchrun` to evaluate the model on multiple GPUs, (e.g., 2 3090 GPUs here), I get an RuntimeError as follows:

```
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/CLIPSelf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/anaconda3/envs/CLIPSelf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/codebase/CLIPSelf/src/training/main.py", line 352, in <module>
    main(sys.argv[1:])
  File "/home/xxx/codebase/CLIPSelf/src/training/main.py", line 190, in main
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)
  File "/home/xxx/anaconda3/envs/CLIPSelf/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/xxx/anaconda3/envs/CLIPSelf/lib/python3.9/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
```

As the error message shows, this error occurs when `model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[device], **ddp_args)`. When I use 1 GPU, the code runs successfully. Anybody knows why does this happen?

**Comment by xuxiangqian** [comment]
我是跟新代码后也是这样的错误？

**Comment by rwightman** [comment]
this looks like an environment / hadware issue as this has been used extensively in multi-gpu setups, including simple 2-4 GPU torchrun like this on my home 3090. 

For reference, I just did a run the other week with this cmd line `torchrun --nproc-per-node 4 -m training.main --train-data '/data/cc12m/cc12m-train-{0000..2175}.tar' --train-num-samples 10968539 --imagenet-val /data/imagenet/validation/ --batch-size 1024 --grad-checkpointing --model convnext_tiny --beta2 0.98 --eps 1e-6 --grad-clip-norm 5.0 --lr 5e-4 --workers 6 --siglip`

**Comment by lcxrocks** [comment]
There is a high possibility that you got a duplicate log name, which can cause the process to hang up and output the Timeout error. If this is the case, specify another new log name would suffice.
<img width="1439" alt="github issue" src="https://github.com/mlfoundations/open_clip/assets/43922196/b589f197-79ba-4e5e-8133-96d05e0a1077">
