### ISSUE TITLE
[BUG] `TimmModel` doesn't work with all timm models due to keyword arg differences

### ISSUE THREAD

**Issue by rsomani95** [mlfoundations/open_clip#676]
`TimmModel` fails to initialise when trying to use the `ghostnet_100` architecture. My model config JSON is setup as follows and is named `ghostnet.json`:

```json
{
    "embed_dim": 640,
    "vision_cfg": {
        "timm_model_name": "ghostnet_100",
        "timm_model_pretrained": false,
        "timm_pool": "",
        "timm_proj": "mlp_cinemanet",
        "timm_drop": 0.0,
        "timm_drop_path": 0.1,
        "image_size": 256
    },
    "text_cfg": {
        "context_length": 77,
        "vocab_size": 49408,
        "width": 640,
        "heads": 10,
        "layers": 12
    }
}
```

When I try to instantiate the model as follows:

```python
import open_clip
model = open_clip.create_model("ghostnet")
```

I fail with this error:
```python
File ~/miniconda3/envs/rosetta/lib/python3.8/site-packages/timm/models/ghostnet.py:351, in _create_ghostnet(variant, width, pretrained, **kwargs)
    320 cfgs = [
    321     # k, t, c, SE, s 
    322     # stage1
   (...)
    344     ]
    345 ]
    346 model_kwargs = dict(
    347     cfgs=cfgs,
    348     width=width,
    349     **kwargs,
    350 )
--> 351 return build_model_with_cfg(
    352     GhostNet,
    353     variant,
    354     pretrained,
    355     pretrained_filter_fn=checkpoint_filter_fn,
    356     feature_cfg=dict(flatten_sequential=True),
    357     **model_kwargs,
    358 )

File ~/miniconda3/envs/rosetta/lib/python3.8/site-packages/timm/models/_builder.py:381, in build_model_with_cfg(model_cls, variant, pretrained, pretrained_cfg, pretrained_cfg_overlay, model_cfg, feature_cfg, pretrained_strict, pretrained_filter_fn, kwargs_filter, **kwargs)
    379 # Instantiate the model
    380 if model_cfg is None:
--> 381     model = model_cls(**kwargs)
    382 else:
    383     model = model_cls(cfg=model_cfg, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'drop_path_rate'
```

---

This is happening because of these lines in the `timm_model.py` file:
https://github.com/mlfoundations/open_clip/blob/e7b39e4321b2c59e7dc2cdf83cddd7742cd9e6a0/src/open_clip/timm_model.py#L52-L55

The `GhostNet` class doesn't accept `drop_path_rate` or `patch_drop_rate` on init ([reference](https://github.com/huggingface/pytorch-image-models/blob/68b2824e49c8a4442ca1c7fb29d3de8135e87c64/timm/models/ghostnet.py#L187-L196)).

I was able to hackily fix this by modifying `timm_model` as follows:

```python
        # if "ghostnet" in model_name:
        if not "convnext" in model_name:
            timm_kwargs['drop_rate'] = drop_path
        else:
            if drop_path is not None:
                timm_kwargs['drop_path_rate'] = drop_path
            if patch_drop is not None:
                timm_kwargs['patch_drop_rate'] = patch_drop
```

---

I imagine this extends to more models in the timm library. Perhaps this was originally written to support only the ConvNext architectures? Does the workaround I suggested above make sense for the time being? I do now know which timm architectures this would be relevant for.

Happy to put in a PR if it makes sense.

**Comment by rsomani95** [comment]
May have been a bug on my end, apologies. Will re-open after testing a little more thoroughly

**Comment by rwightman** [comment]
@rsomani95 remove `"timm_drop_path": 0.1,` from the model cfg

**Comment by rsomani95** [comment]
@rwightman thanks, that's a much simpler fix than I'd expected
