### ISSUE TITLE
MetaCLIP models release in stable version

### ISSUE THREAD

**Issue by vishaal27** [mlfoundations/open_clip#678]
Hey, I see that the metaclip models are added in the repository, but the stable version 2.22.0 does not have them incorporated, do you have a planned stable release with them?

**Comment by vishaal27** [comment]
Awesome, thanks!

**Comment by vishaal27** [comment]
Hey @gabrielilharco, sorry for checking back again, but it doesn't seem that there's a stable version 2.23.0 out yet, atleast the pip handler doesn't seem to be able to find it. Just wondering if the release was indeed triggered? Thanks!

**Comment by rom1504** [comment]
You can follow https://github.com/mlfoundations/open_clip/pull/679

We're waiting for #660 to be merged before releasing as it includes an important fix

**Comment by vishaal27** [comment]
Ahh I see, will follow that PR, thanks.
