### ISSUE TITLE
Usage of title and/or description column in YFCC100M

### ISSUE THREAD

**Issue by Lauler** [mlfoundations/open_clip#7]
Hello,

In your training of CLIP, did you use only the `description` column as text input, or both the `title` and `description` columns?

The reason I am asking is because in the github folder where OpenAI provide info on their [YFCC100M subset](https://github.com/openai/CLIP/blob/main/data/yfcc100m.md), there is a sentence that I find quite ambiguous:

> [...] which have been filtered to only keep those with natural languag titles and/or descriptions in English

This seems to imply that it sufficed that only one of `title` and `description` was considered natural language for an observation (image) to be kept as part of the subset. However, they do not clarify whether they also proceeded to use the results of this natural language filter to choose whether to use only the `title` or only the `description` in the case that one of them was not deemed to be natural language. Alternatively, they may have concatenated the columns and used both of them in training. 

Anyway, what I'm interested in knowing here is what you guys decided to do in your training. Did you use both columns or just the `description`? 

Also, did you clean the text in any manner (e.g. remove html tags present in the text)?

**Comment by Ascn89** [comment]
I am also looking into an answer as the dataset looks a bit messy. 
By any chance could you provide the script where you cleaned up the `title` and/or `description`?

**Comment by Lauler** [comment]
@Ascn89 A first suggestion for you would be something like this:

```python
import pandas as pd
import urllib

df["title"] = df["title"].replace(np.nan, "", regex=True)
df["description"] = df["description"].replace(np.nan, "", regex=True)
df["title"] = df["title"].apply(lambda x: str.replace(urllib.parse.unquote(x), "+", " "))
df["description"] = df["description"].apply(
    lambda x: str.replace(urllib.parse.unquote(x), "+", " ")
)
```

However, the level of cleaning necessary to match the published results is uncertain, and I hope authors of this repo can enlighten us.

**Comment by gabrielilharco** [comment]
Hi @Lauler, in our experiments we used a concatenation of `title` and `description`, with a little bit of cleaning. Hope this helps!

Useful functions:
```python
def remove_html(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

def clean_text(x):
    return remove_html(ftfy.fix_text(urllib.parse.unquote_plus(x)))
``` 

What we use for the text side for each sample:

```python
text = clean_text(table['title'][idx] + ' ' + table['description'][idx])[:500]
```

**Comment by Lauler** [comment]
Thank you that is very helpful!
