### ISSUE TITLE
Split zero-shot and retrieval results csv files

### ISSUE THREAD

**Issue by rwightman** [mlfoundations/open_clip#706]
I feel the results csv has been getting a lot of eyes with it here closer to the models, esp with the new model additions.

Would it be worth adding retrieval results in a separate csv?

**Comment by gabrielilharco** [comment]
We have Flickr and COCO retrieval numbers on that table, are you thinking of some other datasets?

**Comment by gabrielilharco** [comment]
Right now we show average R@1 (image-to-text and text-to-image), but maybe we should expand this to show a breakdown (also R@5, R@10)

**Comment by rwightman** [comment]
@gabrielilharco ah, didn't even realize that was retrieval w/o the R@

**Comment by rwightman** [comment]
although, might make sense to break out into a diff table as zero-shot ranking and retrieval ranking be of separate interest to many down stream uses and those rankings are clearly different...

**Comment by rwightman** [comment]
further, if we split retrieval into its own csv, makes sense to add more columns (@1, @5, @10,  image-to-text, and text-to-image) also useful because comparing to papers there isn't always consistency in terms of which numbers they're using

**Comment by gabrielilharco** [comment]
Will do @rwightman. We also have WinoGAViL as part of the 38 datasets (https://arxiv.org/abs/2207.12576). Maybe we can leave those three datasets (Flickr, MSCOCO and WinoGAViL) in the main table for completion and consistency with the datacomp benchmark, and keep a separate table for the three retrieval datasets?

**Comment by rwightman** [comment]
@gabrielilharco yeah, could leave the main table as is, the full summary (also the link is out there so shouldn't change the name)... maybe even split of a zs-only variant since it's just post-filtering? I think more people would be happy to see a more detailed retrieval table as it's a big use case for these models.

**Comment by gabrielilharco** [comment]
Agreed, just did a PR, let me know how those look to you. Was surprised at how the rankings change!

**Comment by rwightman** [comment]
@gabrielilharco awesome, yeah that's pretty useful to have them organized like this!
