### ISSUE TITLE
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by susht3** [mlfoundations/open_clip#714]
when i load model by clip，i get this error，how to solve this problem?

**Comment by gabrielilharco** [comment]
Hi @susht3 , can you give more details? What model are you trying to load and how are you trying to load it? Could you also post the full error message?

**Comment by rwightman** [comment]
possibly a corrupt checkpoint? although not at all clear what's being done here? loading in c++ via libtorch?
