### ISSUE TITLE
`SigLipTokenizer` and `get_reduction_mask_fn` are unused

### ISSUE THREAD

**Issue by bryant1410** [mlfoundations/open_clip#718]
The class `SigLipTokenizer` and the function `get_reduction_mask_fn`, both from tokenizer.py, are unused. I wonder if it's because of some feature in progress or because they are now redundant with something else?

**Comment by rwightman** [comment]
get_reduction_mask can be used https://github.com/mlfoundations/open_clip/blob/d0befe114486a51b109bfc307fa3fbcaa3283b8b/src/open_clip/tokenizer.py#L163

SigLipTokenizer was used to import sentencepiece vocab files into HF T5 tokenizer, not currently used by the models but would be needed for another import with a different vocab.

**Comment by bryant1410** [comment]
> get_reduction_mask can be used
> 
> https://github.com/mlfoundations/open_clip/blob/d0befe114486a51b109bfc307fa3fbcaa3283b8b/src/open_clip/tokenizer.py#L163

👍🏼 

> SigLipTokenizer was used to import sentencepiece vocab files into HF T5 tokenizer, not currently used by the models but would be needed for another import with a different vocab.

Gotcha. What if we moved it to a script file that does what you describe?
