### ISSUE TITLE
Long text encoding requirements

### ISSUE THREAD

**Issue by mssssss123** [mlfoundations/open_clip#730]
Hello, I would like to thank you for helping my research with your excellent project！
I want to train a CLIP model that can encode longer text(The current 77 length is too small for me). Does the framework itself support this? If not, please give me some modification suggestions😊

**Comment by gabrielilharco** [comment]
Hi @mssssss123. Yes, there is a `context_length` parameter in the configs (e.g. see https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model_configs/ViT-L-14.json)

**Comment by rwightman** [comment]
aside from using context_length with the default tokenizer, you can also define a model using a HF text tower of your choice, eg https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model_configs/xlm-roberta-large-ViT-H-14.json

there's also this biomed CLIP as an example
https://huggingface.co/microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224/blob/main/open_clip_config.json

**Comment by mssssss123** [comment]
Thank you for your help!

**Comment by alexwangmac** [comment]
@gabrielilharco Hi, I want to know, after the value of context_length increases, for example, if the value has been set as 1024 (default is 77), will it affect the inference result, such as the similarity results between images and text? Since the context_length exceeds 77 was not trained right?
