### ISSUE TITLE
Request for Access to Visual Encoder Attention Weights

### ISSUE THREAD

**Issue by LALBJ** [mlfoundations/open_clip#732]
Hello,

Firstly, I would like to express my gratitude for your outstanding project, which has greatly facilitated my research.

As indicated by the title, I’m interested in obtaining the attention weights from the visual encoder. However, upon inspecting the code, I was unable to locate an entry point for retrieving this information. Could you please guide me on how to achieve this?

I have considered the following possible solutions:

1. Custom Attention Layer: This would involve storing the attention weights during the forward pass.
2. Forward Hook: Registering a forward hook to capture the attention weights during the forward pass.

I would appreciate it if you could confirm whether there is an existing method for retrieving attention weights. If not, could you provide any suggestions or feedback on the solutions I’ve proposed?

Thank you for your time and assistance.

**Comment by gabrielilharco** [comment]
Hi @LALBJ. You're right that we don't currently support this in our codebase. Both paths you suggested are possible, using a forward hooks is perhaps the more elegant way to go. If you're looking for some inspiration, you may be interested in this: https://colab.research.google.com/github/kevinzakka/clip_playground/blob/main/CLIP_GradCAM_Visualization.ipynb

**Comment by LALBJ** [comment]
@gabrielilharco, thank you for your help! I appreciate your time and effort.
