### ISSUE TITLE
Why T5 tokenizer vocab size dose not match the token_embedding size in the pretrained siglip model?

### ISSUE THREAD

**Issue by Adenialzz** [mlfoundations/open_clip#735]
Thank you for your trainiing implementation of siglip. I have some question to discuss.
Firstly, I found vocab size in siglip t5 tokenizer is 32_100, but the token_embedding shape in pretrained siglip model is 32_000. May be that is for <extra_id_{n}>? But why these two size do not match. Will there be problem if the input string contains <extra_id_{n}> .
And another question: if I want to add some tokens to siglip t5 vocab (most siglip vocab is englist-only), what should I do? use tokenizer.add_tokens is ok?

**Comment by rwightman** [comment]
@Adenialzz yeah, I think I probably should have disabled the extra ids arg when loading the vocab ... it may cause an issue of thoes tokens are used but think it's fine without? 

You can add extra tokens, but you'd then have to further train the model on multi-lingual content for it to have any impact. 

FYI this model https://huggingface.co/timm/ViT-B-16-SigLIP-i18n-256 is multi-lingual already, but no equivalents for the larger models.

**Comment by Adenialzz** [comment]
Thanks for reply. Maybe we can set extra_ids=0 when initialize T5TokenizerFast. And I extend the en-only vocab and extend the token embedding of TextTransformer correspondingly, it seems to be working well.
