### ISSUE TITLE
no ‘logit_bias’ for DFN2B-CLIP-ViT-L-14

### ISSUE THREAD

**Issue by xiaohu2015** [mlfoundations/open_clip#736]
https://huggingface.co/apple/DFN2B-CLIP-ViT-L-14

```python
import torch
import torch.nn.functional as F
from urllib.request import urlopen
from PIL import Image
from open_clip import create_model_from_pretrained, get_tokenizer 

model, preprocess = create_model_from_pretrained('hf-hub:apple/DFN2B-CLIP-ViT-L-14')
tokenizer = get_tokenizer('ViT-L-14')

image = Image.open(urlopen(
    'https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/beignets-task-guide.png'
))
image = preprocess(image).unsqueeze(0)

labels_list = ["a dog", "a cat", "a donut", "a beignet"]
text = tokenizer(labels_list, context_length=model.context_length)

with torch.no_grad(), torch.cuda.amp.autocast():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    image_features = F.normalize(image_features, dim=-1)
    text_features = F.normalize(text_features, dim=-1)

    text_probs = torch.sigmoid(image_features @ text_features.T * model.logit_scale.exp() + model.logit_bias) # this line don't work

zipped_list = list(zip(labels_list, [round(p.item(), 3) for p in text_probs[0]]))
print("Label probabilities: ", zipped_list)
```

**Comment by gabrielilharco** [comment]
Hi @xiaohu2015. Note that DFN model's weren't trained with a sigmoid loss (like SigLIP). They also don't have a logit bias,. So for computing the probabilities, you want this

```python
logits = model.logit_scale.exp() * image_features @ text_features.T
probs = logits.softmax(dim=-1)
```

**Comment by xiaohu2015** [comment]
> Hi @xiaohu2015. Note that DFN model's weren't trained with a sigmoid loss (like SigLIP). They also don't have a logit bias,. So for computing the probabilities, you want this
> 
> ```python
> logits = model.logit_scale.exp() * image_features @ text_features.T
> probs = logits.softmax(dim=-1)
> ```

thanks

**Comment by edwardguil** [comment]
On a similar vain, I get 'TypeError: ClipLoss.forward() got an unexpected keyword argument 'logit_bias' when attempting to run: 
`python -m training.main \
    --save-frequency 1 \
    --train-data $train \
    --train-num-samples $train_samples \
    --val-data $val \
    --val-num-samples $val_samples \
    --dataset-type webdataset \
    --warmup 10000 \
    --batch-size=16 \
    --lr=1e-3 \
    --epochs=30 \
    --workers=8 \
    --model ViT-B-16-SigLIP \
    --pretrained webli`. That is true for any pretrained model trained without sigmoid loss.
