### ISSUE TITLE
ClipLoss.forward() got an unexpected keyword argument 'logit_bias'

### ISSUE THREAD

**Issue by edwardguil** [mlfoundations/open_clip#737]
When attempting to run any of the SigLIP models with pre-trained weights on webli I am getting an error: 
```shell
TypeError: ClipLoss.forward() got an unexpected keyword argument 'logit_bias'
```

This is produced from running:

```shell
#!/bin/bash
train=$1
val=$2
train_samples=$3
val_samples=$4
python -m training.main \
    --save-frequency 1 \
    --train-data $train \
    --train-num-samples $train_samples \
    --val-data $val \
    --val-num-samples $val_samples \
    --dataset-type webdataset \
    --warmup 10000 \
    --batch-size=16 \
    --lr=1e-3 \
    --epochs=30 \
    --workers=8 \
    --model ViT-B-16-SigLIP \
    --pretrained webli
```

Attempting to run the model with the flag: --siglip, produces `--siglip: command not found`

**Comment by rwightman** [comment]
@edwardguil seems like you have a code mismatch of train script / module

**Comment by nihirv** [comment]
@edwardguil what did you do to fix this? Running into the same issue

**Comment by Brian-ISD** [comment]
How was it solved?

**Comment by alexisdrakopoulos** [comment]
I am also facing this now

**Comment by gshklovs** [comment]
I'm currently struggling with the same issue, and I couldn't find documentation on training a SigLIP model anywhere. 

But in open_clip/factory.py:446-452 it looks like additional args are expected to configure the SigLIP loss function: 

```python

  elif args.siglip:
      assert not args.horovod, "Horovod not currently supported for SigLip"
      return SigLipLoss(
          rank=args.rank,
          world_size=args.world_size,
          dist_impl=args.loss_dist_impl,  # siglip has multiple distributed implementations to choose from
      )
```

I'm assuming that setting the `rank`, `world_size` and `loss_dist_impl` arguments will solve the problem?

**Comment by thishome** [comment]
just setting the **--siglip** flag solves the problem.
