### ISSUE TITLE
Final `logit_scale` for SigLip trained models

### ISSUE THREAD

**Issue by jn2clark** [mlfoundations/open_clip#746]
Hi, 

I was wondering if the final value of the `logit_scale` that the SigLip trained models were trained with is available? 

Thanks

**Comment by gabrielilharco** [comment]
Hey @jn2clark. Yes, you can access them like this:

 ```bash
 >>> model, _, preprocess = open_clip.create_model_and_transforms('ViT-SO400M-14-SigLIP-384', pretrained='webli')
>>> model.logit_scale
Parameter containing:
tensor(4.7215, requires_grad=True)
```

**Comment by jn2clark** [comment]
Thanks @gabrielilharco ! To confirm, that is the final value after pre-training?

**Comment by gabrielilharco** [comment]
Yes, note that you should `exp` this before using it (so in this case, ~112.33). I just double-checked the [big_vision codebase]( https://github.com/google-research/big_vision/blob/main/big_vision/configs/proj/image_text/SigLIP_demo.ipynb) for the SO400M-14@384 model, and it matches what we get in this codebase.
