### ISSUE TITLE
Combining 2 S3 sources

### ISSUE THREAD

**Issue by guillaumeguy** [mlfoundations/open_clip#749]
hi there:

The [documentation](https://github.com/mlfoundations/open_clip/#multiple-data-sources) specifies the use of `::` to concatenate 2 data sources. Does it also work for S3? I am getting an error (Handling webdataset error - no gopen handler defined).

My line looks like this:

```
export TRAINING_DATA="pipe:aws s3 cp ${ROOT_PATH}/folder1/{00000..00019}.tar::${ROOT_PATH}/folder2/{00000..00031}.tar -"
```

Happy to add an example for S3 in the documentation when I nail the right format.

**Comment by guillaumeguy** [comment]
I think I figured it out ... It seems that for S3 piping, one needs to use a comma separated list as illustrated in the example below:

https://github.com/mlfoundations/open_clip/blob/29b90b8dde9125c479c0ddbab477310f665a0435/docs/script_examples/stability_example.sh#L39

Let me know if you want me to clarify in the documentation.

**Comment by gabrielilharco** [comment]
Should also work with two `pipe`s, something like `"pipe:aws s3 cp ${ROOT_PATH}/folder1/{00000..00019}.tar  -::pipe:aws s3 cp ${ROOT_PATH}/folder2/{00000..00031}.tar -"`. You'll need this if you want to mix with different weighting for the different sources.
