### ISSUE TITLE
Question about pretrained = 'openai'

### ISSUE THREAD

**Issue by Anshler** [mlfoundations/open_clip#750]
If I load a the clip model with pretrained = 'openai', does it just load the normal CLIP model? or is it different?

**Comment by gabrielilharco** [comment]
Hey @Anshler. I'm not exactly sure what you mean by "normal", but the `pretrained='openai'` models are the original CLIP models from [Radford et al., 2021](https://arxiv.org/abs/2103.00020)

**Comment by Anshler** [comment]
Yes, I mean if it's the same as the original openai's CLIP model, thanks.
