### ISSUE TITLE
AssertionError: Please install tensorboard.

### ISSUE THREAD

**Issue by ShuxunoO** [mlfoundations/open_clip#752]
Hello~

When I run the commad:

 ```
python -m training.main \

    ……

    --report-to=tensorboard \

    ……
```

I will get an AssertionError:Please install tensorboard.
detailed message is like following:

```
Traceback (most recent call last):
  File "/home/sswang/anaconda3/envs/openclip/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sswang/anaconda3/envs/openclip/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sswang/anaconda3/envs/openclip/lib/python3.10/site-packages/training/main.py", line 508, in <module>
    main(sys.argv[1:])
  File "/home/sswang/anaconda3/envs/openclip/lib/python3.10/site-packages/training/main.py", line 389, in main
    assert tensorboard is not None, "Please install tensorboard."
AssertionError: Please install tensorboard.
```

**But the fact is that I have installed the tensorboard package**

```
conda list tensorboard
# packages in environment at /home/xxx/anaconda3/envs/openclip:
#
# Name                    Version                   Build  Channel
tensorboard               2.15.1             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py310h52d8a92_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

What should I do to ues the tensorboard correctly？

**Comment by gabrielilharco** [comment]
Does this import work for you? `import torch.utils.tensorboard as tensorboard`

**Comment by ShuxunoO** [comment]
> ![image](https://private-user-images.githubusercontent.com/40421448/287133167-a4580ab1-7cb4-42f8-b693-4e1532dbf46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjY1NjUsIm5iZiI6MTcwMTQyNjI2NSwicGF0aCI6Ii80MDQyMTQ0OC8yODcxMzMxNjctYTQ1ODBhYjEtN2NiNC00MmY4LWI2OTMtNGUxNTMyZGJmNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDEwMjQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZDBiNjIxZjQyOWFiZGEyNTZmMmMwNzU3MGM2MmYyZDNmOGQ2MjhiNzE4MmEzNThiMmU2NzY0ZDE3Mzk4NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LwLVXmV_ziYFH0TdX8zHxXq0q201TYMfKdkyftaCHxU)
> 
> Yes，it works well

but when I run the official command line, it will report the **AssertionError: Please install tensorboard.** again

**Comment by gabrielilharco** [comment]
I suspect there's a mismatch between the environment you are using to run open_clip and the one you installed tensorboard. The assert only fails if the import fails (see https://github.com/mlfoundations/open_clip/blob/main/src/training/main.py#L21)

**Comment by ShuxunoO** [comment]
I re-install my conda env， it works this time

detailed installation package information is like following:

```
……

python                    3.10.13
tensorboard               2.15.1 
tensorboard-data-server   0.7.2
torch                     2.0.1+cu118         
torch-tb-profiler         0.4.3           

……
```

It‘s very kind of you! Thank you very much!
