### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CLIP

### ISSUE THREAD

**Issue by ShuxunoO** [mlfoundations/open_clip#757]
When I want to use **EVA02_CLIP_L_psz14_s4B.pt** to extract some img features, I try to follow the  steps below to load the model:

```
    model_path = "/disk1/xxx/NFTSearch/models/clip/EVA02_CLIP_L_psz14_s4B.pt"
    tokenizer_type = "ViT-L-14"
    tensor_cache_storage_path = Path("/disk1/xxx/Tensor_cache/NFT1000_mini/EVA-CLIP_vit_l_14_pretrained")
    model, _, preprocess = open_clip.create_model_and_transforms(tokenizer_type, pretrained=model_path, device=device)
    tokenizer = open_clip.get_tokenizer(tokenizer_type)
    model.to(device)
```

But it meets some error:

> RuntimeError: Error(s) in loading state_dict for CLIP:
> 	Missing key(s) in state_dict: "positional_embedding", "text_projection", "visual.class_embedding", "visual.positional_embedding", "visual.proj", "visual.conv1.weight", ……

	
The model is downloaded from official huggingface link :[https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA02_CLIP_L_psz14_s4B.pt](https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA02_CLIP_L_psz14_s4B.pt)

How to handle the error or can I only use the[ EVA-CLIP official GitHub repository](https://github.com/baaivision/EVA/tree/master/EVA-CLIP) to extract features?

**Comment by rwightman** [comment]
@ShuxunoO `open_clip.create_model_and_transforms('EVA02-L-14', pretrained='merged2b_s4b_b131k')`

**Comment by ShuxunoO** [comment]
Thank you a lot!
