### ISSUE TITLE
Inference for non-square images

### ISSUE THREAD

**Issue by SimJeg** [mlfoundations/open_clip#76]
Hello, 

I would like to run the different CLIP models on high definition non-square images (e.g. 720p or 1080p). 
Is there a simple way to do so without deforming the images into a smaller square resolution (336x336 or 224x224) ?

Thank you for your work on this repository, I found it very helpful,
Simon

**Comment by SimJeg** [comment]
Thank you for your quick reply @rom1504 

For my use case I have to detect small objects on high resolution images, so the multiple crops strategy would be the most appropriate. But doing so you loose some context ! 

I will investigate how to adapt the code for 512x512 or 1024x1024

**Comment by rom1504** [comment]
The pretrained model takes 224x224 as input and training larger resolution models is pretty costly.
So finding a way to fit your input image in 224x224 is the most reasonable solution.
You may decide to use both a "whole image" crop and a bunch of smaller crops from inside the image, compute embeddings of that then feed that to your downstream application (classifier, Knn,...)

**Comment by rwightman** [comment]
@SimJeg in addition to @rom1504's comments, I will warn you that increasing the resolution in a ViT model results in a SIGNIFICANT increase in compute & memory consumption. Also, with classic vit that uses absolute pos embed, you cannot change the resolution without interpolating the position embedding, and that has an impact on performance unless you fine-tune again. 

I'm looking at working on a relative position embed that can be rescaled, but the current models don't support that.

**Comment by SimJeg** [comment]
Thank you for your detailed comments. I may compare the different
strategies and post results here if I get interesting insights. So far I
have results aligned with the CLIP paper results  ***@***.***  > ViT-L14 >
ViT-B16 > RN50).

I benchmarked a few other extractors (e.g. iBOT, SWAG RegNet, EfficientNet)
but CLIP embeddings are the best ! I get better results with SWAG on
512x512 images than with with 224x224 images (which is the pretrained
resolution) which the reason of this issue.

Le jeu. 28 avr. 2022 à 22:55, Ross Wightman ***@***.***> a
écrit :

**Comment by SimJeg** [comment]
Hello, 

I did not have time to investigate the performances of the different models on higher image resolutions (e.g. 512x512).  I used a multi-crop strategy and get a significant boost in performances both in zero-shot and finetuning (linear and full). @rom1504  @rwightman  feel free to close this issue and thank you again for your amazing work :)

**Comment by rwightman** [comment]
@SimJeg thanks for the report. I've got some convnext fiddling in the works, so many some more 'resizable' models in the future...
