### ISSUE TITLE
how to convert my trained openclip model "epoch_499.pt" to huggingface (hf) format (.bin) ?

### ISSUE THREAD

**Issue by jzssz** [mlfoundations/open_clip#766]
I'm very anxious about this issue. thanks a lot !!!!!!

**Comment by gabrielilharco** [comment]
Hi @jzssz, please see https://github.com/mlfoundations/open_clip?tab=readme-ov-file#pushing-models-to-hugging-face-hub

**Comment by mittski** [comment]
> Hi @jzssz, please see https://github.com/mlfoundations/open_clip?tab=readme-ov-file#pushing-models-to-hugging-face-hub

Any chance of an update to be able to run this conversion locally?
I've successfully done it, but for later users; it really is a hassle to create a HF account, private repo, write token, juggle HF CLI, upload your model and redownload it as .bin when the .pt to .bin path is, presumably, already downloaded and ready to roll without all that. 
Or, maybe I'm mistaken (most of this repo's code really is beyond me) and the .pt-> .bin actually handled by huggingface servers?
