### ISSUE TITLE
Code for zero-shot classification with CoCa 

### ISSUE THREAD

**Issue by shivam-chandhok** [mlfoundations/open_clip#768]
Hi,
Can you provide a short code to do zero-shot classification (based on cosine similarity similar to CLIP ) with CoCa model.??

**Comment by gabrielilharco** [comment]
CoCa models can also contrast images and text, so you can use them in the same way you use other CLIP models for zero-shot classification. CLIP benchmark (https://github.com/LAION-AI/CLIP_benchmark#how-to-use) has support for many common datasets in case you are interested
