### ISSUE TITLE
Will MetaCLIP be evaluated and put into the openclip_results.csv?

### ISSUE THREAD

**Issue by yxchng** [mlfoundations/open_clip#769]

**Comment by gabrielilharco** [comment]
Yes, we have evals for 7 MetaCLIP models there (search for `metaclip_400m`  or `metaclip_fullcc` in the pretrained column). Are you looking for a specific model that is not there?

**Comment by gabrielilharco** [comment]
Closing for now, feel free to re-open if we're missing something
