### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._C._distributed_rpc'; 'torch._C' is not a package

### ISSUE THREAD

**Issue by kisenera** [mlfoundations/open_clip#77]
I get this strange error when attempting "import open_clip". I have tried reinstalling open clip, as well as various versions of pytorch. In this instance, I am using python 3.7.9 and pytorch 1.9.0.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\firewolf\AppData\Local\Programs\Python\Python37\lib\site-packages\open_clip_torch-1.0.1-py3.7.egg\open_clip\__init__.py", line 2, in <module>
    from .loss import ClipLoss
  File "C:\Users\firewolf\AppData\Local\Programs\Python\Python37\lib\site-packages\open_clip_torch-1.0.1-py3.7.egg\open_clip\loss.py", line 2, in <module>
    import torch.distributed.nn
  File "C:\Users\firewolf\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\nn\__init__.py", line 1, in <module>
    from .api.remote_module import RemoteModule
  File "C:\Users\firewolf\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\nn\api\remote_module.py", line 22, in <module>
    from torch.distributed.rpc.internal import _internal_rpc_pickler
  File "C:\Users\firewolf\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\distributed\rpc\internal.py", line 12, in <module>
    from torch._C._distributed_rpc import _get_current_rpc_agent
ModuleNotFoundError: No module named 'torch._C._distributed_rpc'; 'torch._C' is not a package
```

**Comment by rwightman** [comment]
@kisenera you are on windows and torch distributed doesn't import properly. I might be able to add an import guard for that

**Comment by illtellyoulater** [comment]
Wow it seams that for some reason this page was not indexed by google and it took me AGES to find it (actual days, span across weeks...). Apparetnly we are the only two people on the earth with this specific problem...

@rwightman: the import-guard you mentioned would just be a mechanism to avoid the loading of the problematic module? Correct? Or were you implying that this could somehow fix the problem? (sorry but I'm rather new to Python).

@kisenera have you found a way to make this work ? Or any workarounds? 

Please  @rwightman @kisenera let me know asap, as I already lost so much time on this!
Thanks a lot in adv!

**Comment by dblunk88** [comment]
> Wow it seams that for some reason this page was not indexed by google and it took me AGES to find it (actual days, span across weeks...). Apparetnly we are the only two people on the earth with this specific problem...
> 
> @rwightman: the import-guard you mentioned would just be a mechanism to avoid the loading of the problematic module? Correct? Or were you implying that this could somehow fix the problem? (sorry but I'm rather new to Python).
> 
> @kisenera have you found a way to make this work ? Or any workarounds?
> 
> Please @rwightman @kisenera let me know asap, as I already lost so much time on this! Thanks a lot in adv!

Only 3 :)

**Comment by rwightman** [comment]
@illtellyoulater @dblunk88 @kisenera can someone confirm whether the latest updates on main branch fix this issue?

**Comment by kisenera** [comment]
Yes it works, thanks

**Comment by illtellyoulater** [comment]
@rwightman can confirm it works! Thank you!!!
