### ISSUE TITLE
Question: Are the CLIP tokenizers case sensitive?

### ISSUE THREAD

**Issue by thomasf1** [mlfoundations/open_clip#773]
Sorry for the question, I´ve seen a number of zero shot models using case sensitive text (sometimes with double entires with different uper and lower case characters), so I was wondering if the tokenisers are case sensitive and if it´s model dependent how to find out if they are...

**Comment by gabrielilharco** [comment]
Hi @thomasf1, we have a few different tokenizers for different models, so best to check the one you're using. Here's a simple way to do this, check if the outputs are equal or not

```python
import open_clip
tokenizer = open_clip.get_tokenizer('ViT-B-32')
print(tokenizer(['test', 'TEST', 'Test']))
```

**Comment by thomasf1** [comment]
Thank you :)

Do you know if there is some data showing a benefit of keeping the upper/lowercase?
