### ISSUE TITLE
Confirmation: Pretraining is Non-Deterministic?

### ISSUE THREAD

**Issue by RylanSchaeffer** [mlfoundations/open_clip#776]
We're pretraining small CLIP models and finding that the exact same pretraining runs differ from one another slightly. We see that the code is seeded, so we were initially surprised, but then we found this issue:

https://github.com/mlfoundations/open_clip/issues/734

To confirm, is the pretraining code non-deterministic? If so, is there a way to make pretraining deterministic?

**Comment by mitchellnw** [comment]
Yes non-determinism is expected right now, sorry.

**Comment by RylanSchaeffer** [comment]
Thank you for confirming!

**Comment by rwightman** [comment]
@RylanSchaeffer you can make the dataset deterministic by trying what was metnioned in #734 ... complete training determinism in PyTorch on a GPU is a whole nother matter entirely and you can lookup what that entails, it tends to be non-trivial and a performance tradeoff.

**Comment by RylanSchaeffer** [comment]
I actually don't need determinism. I just wanted to confirm that different runs were producing slightly different results because training was non-deterministic. If that wasn't the case, I would have needed to investigate what I was doing wrong!
