### ISSUE TITLE
Model config for laion2b_s34b_b88k not found

### ISSUE THREAD

**Issue by ha1ha2hahaha** [mlfoundations/open_clip#790]
when i load the model
`model, _, _ = create_model_and_transforms(model_name="laion2b_s34b_b88k", pretrained="clip/open_clip_pytorch_model.bin")`

    raise RuntimeError(f'Model config for {model_name} not found.')
RuntimeError: Model config for laion2b_s34b_b88k not found.

https://github.com/mlfoundations/open_clip/issues/528 provides some information, but it not worked to me！

**Comment by rwightman** [comment]
@ha1ha2hahaha reread #528 you put the tag in the model name field
