### ISSUE TITLE
Model weights missing ViT-SO400M-14-SigLIP-384 (webli pretrained)

### ISSUE THREAD

**Issue by anshudaur** [mlfoundations/open_clip#809]
HI, 

Thank you for the great work! 

I selected 'ViT-SO400M-14-SigLIP-384' model (pretrained: webli) and it seems this model is missing the weights.

Can you please share it ?

Thank you
Anshu

**Comment by gabrielilharco** [comment]
Hi @anshudaur, do you have the latest versions of openclip and timm?

**Comment by anshudaur** [comment]
Yes, now i can use the weights, i didn't update the repo . Thank you.
