### ISSUE TITLE
Logging for cuda usage could be a little confused when specifying gpu-id

### ISSUE THREAD

**Issue by Vikho** [mlfoundations/open_clip#829]
When I use the training script and specify` export CUDA_VISIBLE_DEVICES=1`, the logging shows` _cuda:0_`, which is inconsistent with the actual usage (indeed using `cuda:1`). This may cause some confusion for those who are new to GPU deep learning.

**Comment by rwightman** [comment]
using CUDA_VISIBLE_DEVICES is a low level alteration, it changes the device enumeration visible to the application so 0 is what the application sees.
