### ISSUE TITLE
```coca_base``` configuration does not have any ```pretrained``` arguments

### ISSUE THREAD

**Issue by shyammarjit** [mlfoundations/open_clip#837]
While trying zero-shot evaluation, the ```coca_base``` configuration with ```pretrained=''``` gives very less accuracy. Please verify the ```coca_base``` configuration.

**Comment by rwightman** [comment]
There are two pretrained tags for CoCa B/32, if you're using an empty string '' it's not loading a pretrained checkpoint so it's random init.

laion2b_s13b_b90k=_pcfg(hf_hub='laion/CoCa-ViT-B-32-laion2B-s13B-b90k/'),
mscoco_finetuned_laion2b_s13b_b90k=_pcfg(hf_hub='laion/mscoco_finetuned_CoCa-ViT-B-32-laion2B-s13B-b90k/'
