### ISSUE TITLE
braceexpand has unexpected (non-bash-like) behavior with multiple expansions

### ISSUE THREAD

**Issue by carlini** [mlfoundations/open_clip#84]
If you provide bash a command like "foo{0..5} bar{1..6}" it will expand each of the brace expansions separately, give you a list of length 10. Braceexpand will do the cross product here though, and give a list of length 25. This isn't necessarily wrong in general, but in the case of how braceexpand is used in this project I think it's not what's expected.

In particular, if you provide --train-data="/dir1/files{1..10} /dir2/files{1..10}" it ends up trying to include 100 (!!) files. It would probably make more sense to do the bash-like expansion here.

**Comment by rwightman** [comment]
@carlini I was actually wondering about this use case (multiple folders or datasets in different locations) and whether it'd work via command line or not... I was going to combine yfcc and cc12m on my local machine soon so I'll sort this out.

**Comment by ChengJiacheng** [comment]
Hi @rwightman , thanks you for the great work!
I am also very interested in training with the combination of multiple datasets (under different folders). My current plan is se `train-data` as something like `shards='/data/{yfcc/{00000..00010},cc12m/{00000..00010}}.tar'`, so that the expanded list will be like 
```
>>> print( list(braceexpand.braceexpand(shards)) )

['/data/yfcc/00000.tar',
 '/data/yfcc/00001.tar',
 '/data/yfcc/00002.tar',
 '/data/yfcc/00003.tar',
 '/data/yfcc/00004.tar',
 '/data/yfcc/00005.tar',
 '/data/cc12m/00000.tar',
 '/data/cc12m/00001.tar',
 '/data/cc12m/00002.tar',
 '/data/cc12m/00003.tar',
 '/data/cc12m/00004.tar',
 '/data/cc12m/00005.tar']
```
Do you think this will work or there is a better solution for this? Any comments or suggestion will be greatly appreciated. Thank you!

**Comment by rom1504** [comment]
```
>>> list(braceexpand('/data/{yfcc/{00000..00010},cc12m/{00000..00010}}.tar'))
['/data/yfcc/00000.tar', '/data/yfcc/00001.tar', '/data/yfcc/00002.tar', '/data/yfcc/00003.tar', '/data/yfcc/00004.tar', '/data/yfcc/00005.tar', '/data/yfcc/00006.tar', '/data/yfcc/00007.tar', '/data/yfcc/00008.tar', '/data/yfcc/00009.tar', '/data/yfcc/00010.tar', '/data/cc12m/00000.tar', '/data/cc12m/00001.tar', '/data/cc12m/00002.tar', '/data/cc12m/00003.tar', '/data/cc12m/00004.tar', '/data/cc12m/00005.tar', '/data/cc12m/00006.tar', '/data/cc12m/00007.tar', '/data/cc12m/00008.tar', '/data/cc12m/00009.tar', '/data/cc12m/00010.tar']
```

it seems this works
let's document this in readme and then close this

**Comment by rom1504** [comment]
fixed now
