### ISSUE TITLE
How to load Clip-VIT-bigG-14 in local which has two .bin files and can not find any information how to load, thanks!!!!!!!

### ISSUE THREAD

**Issue by hanggun** [mlfoundations/open_clip#841]

**Comment by hanggun** [comment]
解决了，下载了open_clip_model就可以加载了

**Comment by rwightman** [comment]
Use the `https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/blob/main/open_clip_pytorch_model.bin` and pass as the pretrained arg.

**Comment by xpdd123** [comment]
> 解决了，下载了open_clip_model就可以加载了

怎么解决的,只要下载这个文件就可以吗?有代码吗
