### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by wujohns** [mlfoundations/open_clip#847]
The coca model demo not work and the wrong code is here:
```py
# open_clip/coca_model.py 
...
if beam_scorer.is_done or stopping_criteria(input_ids, None):
  break
...
```

the beam_scorer.is_done is like: ensor(False, device='cuda:0')
the stopping_criteria(input_ids, None) is like:  tensor([False, False, False, False, False, False], device='cuda:0')

the beam_scorer.is_done or stopping_criteria(input_ids, None) is like tensor([False, False, False, False, False, False], device='cuda:0')
but when you run `if tensor([False, False, False, False, False, False], device='cuda:0') ` it will case RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by Aristotelis1** [comment]
I had the same issue and I tried a different `generation_type` to be able to generate captions for now

**Comment by ialhashim** [comment]
@Aristotelis1 suggestion works ` generation_type=`

**Comment by colton138** [comment]
Hi, has there been a fix that includes beam_search? 
having the same issue but as mentioned, changing `generation_type` does work.

**Comment by OrderJade** [comment]
> I had the same issue and I tried a different `generation_type` to be able to generate captions for now

bro,what exactly is your operational process?

**Comment by colton138** [comment]
> > I had the same issue and I tried a different `generation_type` to be able to generate captions for now
> 
> bro,what exactly is your operational process?

The Coca model demo in the repo  that's in a colab

**Comment by MengqingCao** [comment]
There is a resolution in #860, hope it helps. : )

**Comment by colton138** [comment]
> There is a resolution in #860, hope it helps. : )

Thank you!

**Comment by eware-godaddy** [comment]
If you can't wait for #860 to be merged, you can roll back to the `transformers==4.38.2` which is the last version before the change.

This is the [commit](https://github.com/huggingface/transformers/commit/8f2f0f0f85f9e517c495b2083c218215819bae34) that broke this, and it was introduced in `4.39.0`
