### ISSUE TITLE
Training speed slow

### ISSUE THREAD

**Issue by lezhang7** [mlfoundations/open_clip#861]
Hi,

I found that training speed was slow down if number of gpus is more than 2, is it because more gpus brings larger batch size to compute and gather_all will take up some time?

Best

**Comment by rwightman** [comment]
@lezhang7 you see less samples per second per gpu as you increase the # of gpus, but the total samples / sec should increase until you saturate your interconnect. You could have a broken distributed setup if more than two causes a significant slowdown. Or slow disks causing IO bottlenecks reading your dataset...
