### ISSUE TITLE
What is the max value for unlocked_groups in TimmModel.lock()? I am trying to fine-tune the entire vision tower

### ISSUE THREAD

**Issue by mikelee-dev** [mlfoundations/open_clip#866]
inside of ```open_clip/src/open_clip /timm_model.py```, there is a function TimmModel.lock() which is stated to allow you to fine tune the model by unfreezing the weights in certain layer groups starting from the head of the model.

What is the max value for param unlocked_groups? I would like to fine tune the entire vision tower for my task. Thanks!

Thanks!

**Comment by rwightman** [comment]
everything is fine-tuned by default, so don't lock if you want to fine-tune the whole tower, freezing works by unlocking groups from the head back, if you don't; freeze there is nothing to worry about unlocking.
