### ISSUE TITLE
increase generality of models

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#88]
does it make sense to add more options to vary the kind of models to use in openclip?

eg would it make sense to be able to plug something like https://huggingface.co/xlm-roberta-large as the language model in openclip training ?
and possibly freeze it

would like your opinion on this @rwightman

**Comment by rwightman** [comment]
@rom1504 this falls under #53 no?

**Comment by rom1504** [comment]
Indeed, closing here
