### ISSUE TITLE
scripts of training on multiple nodes

### ISSUE THREAD

**Issue by cyy857** [mlfoundations/open_clip#9]
Hi, is there any easy-using script for training clip on multiple nodes? I can set up training on one node(8GPUs) now. But I need to test the scaling efficient. Thanks for any insight~

**Comment by mitchellnw** [comment]
see https://github.com/mlfoundations/open_clip/pull/38

**Comment by Zasder3** [comment]
Addressed in #44! Happy to re-open and add clarity if still not in an easy to use place for others :)
