### ISSUE TITLE
Duplicate Class Names in IMAGENET_CLASSNAMES

### ISSUE THREAD

**Issue by raytrun** [mlfoundations/open_clip#917]
I have noticed that the IMAGENET_CLASSNAMES list contains two duplicate categories: "sunglasses" and "missile." Could this duplication potentially negatively impact the evaluation process?

**Comment by rwightman** [comment]
@raytrun this is the way all CLIP models are evaluated on imagenet, so not being changed. That said, I feel changing it will not make the results better, take a look at the images yourself.
