### ISSUE TITLE
Error loading state_dict using pre-trained checkpoint with CustomTextCLIP model

### ISSUE THREAD

**Issue by cubense** [mlfoundations/open_clip#918]
Dear developers:

I recently reinstalled the latest environment for open_clip. When I tried to train new data using a pre-trained checkpoint and model, I encountered an error. The error message indicates that almost all keys in the state_dict are missing or not recognized.

traning parameters are:
train_command = [
        'python', '-m', 'open_clip_train.main',
        '--save-frequency', '1',
        '--zeroshot-frequency', '1',
        '--report-to', 'tensorboard',
        '--train-data', train_csv,
        '--val-data', val_csv,
        '--csv-img-key', 'img_path',
        '--csv-caption-key', 'label',
        '--warmup', '1000',
        '--batch-size', '32',
        '--lr', '5e-6',
        '--wd', '0.1',
        '--epochs', '1000',
        '--workers', '4',
        '--model','hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224',
        '--csv-separator', ',',
        '--pretrained','../models/open_clip-main/logs/-model_coca_ViT-L-14-lr_5e-06-b_64-j_8-p_amp/checkpoints/epoch_20.pt',
        '--val-frequency', '10'
    ]
    subprocess.run(train_command)

Error Message:
RuntimeError: Error(s) in loading state_dict for CustomTextCLIP:
    Missing key(s) in state_dict: "visual.trunk.cls_token", "visual.trunk.pos_embed", "visual.trunk.patch_embed.proj.weight", "visual.trunk.patch_embed.proj.bias", "visual.trunk.blocks.0.norm1.weight", "visual.trunk.blocks.0.norm1.bias", "visual.trunk.blocks.0.attn.qkv.weight", "visual.trunk.blocks.0.attn.qkv.bias", "visual.trunk.blocks.0.attn.proj.weight", "visual.trunk.blocks.0.attn.proj.bias", "visual.trunk.blocks.0.norm2.weight", "visual.trunk.blocks.0.norm2.bias", "visual.trunk.blocks.0.mlp.fc1.weight", "visual.trunk.blocks.0.mlp.fc1.bias", "visual.trunk.blocks.0.mlp.fc2.weight", "visual.trunk.blocks.0.mlp.fc2.bias", ...

I don't know how it happened.

**Comment by rwightman** [comment]
@cubense what I see on that command line is a BiomedCLIP model + an pretrained checkpoint from a coca_ViT-L which are completely incompatible....

**Comment by cubense** [comment]
Sorry, I used a wrong model
