### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by vadim0x60** [mlfoundations/open_clip#931]
My programs crash with a segmentation fault when trying to initialize a model with `create_model_and_transforms` on an Intel Mac. I have tried different devices (cpu, mps) and different models - the crash always happens when positional embeddings get initialized (i.e. `transformer.py:475` or `modified_resnet.py:61`)

May or may not be related to [this issue](https://github.com/pytorch/pytorch/issues/115239), but it is supposed to be already fixed in my version of pytorch (2.2.2). My version of `open_clip_torch` is 2.26.1.

**Comment by vadim0x60** [comment]
UPD: Turns out this depends on order of imports w.r.t. numpy. Here's the minimal example:


```
# This works fine
import open_clip
import numpy as np

model, _, preprocess = open_clip.create_model_and_transforms("ViT-H-14-378-quickgelu")
```

```
# This segfaults
import numpy as np
import open_clip

model, _, preprocess = open_clip.create_model_and_transforms("ViT-H-14-378-quickgelu")
```

**Comment by rwightman** [comment]
I don't think there's anything I can do here,  and it's likely transient across torch / numpy / python versions so closing
