### ISSUE TITLE
 training details for convnext_large_d.laion2B-s26B-b102K-augreg

### ISSUE THREAD

**Issue by mumu-mu** [mlfoundations/open_clip#932]
Hi,

I have been looking for training details for  convnext_large_d.laion2B-s26B-b102K-augreg but couldn't find anything. 
Could you please provide these details? Thanks.

**Comment by rwightman** [comment]
https://huggingface.co/laion/CLIP-convnext_large_d.laion2B-s26B-b102K-augreg#training-procedure
