### ISSUE TITLE
Any Plan for direct support of parquet dataset?

### ISSUE THREAD

**Issue by cxxgtxy** [mlfoundations/open_clip#933]
Great work.
Many datasets (such as https://huggingface.co/datasets/laion/laion400m,  https://huggingface.co/datasets/laion/relaion2B-en-research-safe) have been provided in HF. It would be great if this repo can directly support such data format.

Thanks!

**Comment by rwightman** [comment]
@cxxgtxy those are just the URLs & metadata though, images need to be downloaded from the urls and they're not stable, so it's not a particularly suitable form for training from even if you did make some efficient async fetcher for the images...

Also, generally speaking, the image datasets on the parquet hub are quite a bit less efficient than sharded webdataset training for any decent sized dataset. Most users are training these with fairly large datasets and the overhead of parquet and especially random access is meh.

**Comment by cxxgtxy** [comment]
Thanks!

Ross Wightman ***@***.***> 于2024年9月6日周五 04:50写道：
