### ISSUE TITLE
Load model is Error

### ISSUE THREAD

**Issue by ROC-Star** [mlfoundations/open_clip#934]
Error is  follow:
Pretrained weights (./pre/open_clip_pytorch_model.bin) not found for model ViT-L-14. Available pretrained tags (['openai', 'laion400m_e31', 'laion400m_e32', 'laion2b_s32b_b82k', 'datacomp_xl_s13b_b90k', 'commonpool_xl_clip_s13b_b90k', 'commonpool_xl_laion_s13b_b90k', 'commonpool_xl_s13b_b90k'].

this is my code:
model_name = "ViT-L-14"
pre = 'datacomp_xl_s13b_b90k'
model, _, preprocess = open_clip.create_model_and_transforms(model_name=model_name, pretrained='./pre/open_clip_pytorch_model.bin')

I have downloaded the pre-trained model(open_clip_pytorch_model.bin) locally.

**Comment by rwightman** [comment]
it didn't find a file at that location if it responds with the error that pretrained didn't match one of the builtin tags.

**Comment by rwightman** [comment]
I'd try an absolute path for pretrained= in case it's resolving the relative path incorrectly.
