### ISSUE TITLE
Inconsistent performance on pretrained checkpoints of the same architecture from different sources

### ISSUE THREAD

**Issue by bdevnani3** [mlfoundations/open_clip#936]
Thanks for this wonderful repo. I'd really appreciate some help in debugging the following issue:

I see inconsistent performance when measuring the zero-shot results of a `ViT-B-16` model depending on the pre-trained checkpoint I use.

When I evaluate the pre-trained openai checkpoint like so:
```
srun -u python -m open_clip_train.main \
    --imagenet-val /path/to/imagenet/val \
    --model ViT-B-16 \
    --pretrained openai
```
everything works fine and I get a performance of 

``` Eval Epoch: 0 imagenet-zeroshot-val-top1: 0.683 ; imagenet-zeroshot-val-top5: 0.9188 ```

However, when I try to use the `timm` variant of this model checkpoint from [huggingface](https://huggingface.co/timm/vit_base_patch16_clip_224.openai) by defining my config file at `src/open_clip/model_configs/vit_base_patch16_clip_224.json` like so:

```
{
    "embed_dim": 512,
    "vision_cfg": {
        "timm_model_name": "vit_base_patch16_clip_224.openai",
        "timm_model_pretrained": true,
        "timm_pool": "",
        "timm_proj": "linear",
        "image_size": 224
    },
    "text_cfg": {
        "context_length": 77,
        "vocab_size": 49408,
        "width": 512,
        "heads": 8,
        "layers": 12
    }
} 
```

and using the following command to kick off evaluation:

```
srun -u python -m open_clip_train.main \
    --imagenet-val /path/to/imagenet/val \
    --model vit_base_patch16_clip_224 
 ```
 I see the performance drop to 
```Eval Epoch: 0 imagenet-zeroshot-val-top1: 0.0008; imagenet-zeroshot-val-top5: 0.0040```
 
 
As far as I see in the logs, the pre-trained weights download successfully in both cases. Am I missing something when defining the model config in case 2?

Thank you!

**Comment by rwightman** [comment]
@bdevnani3 it's not inconsistent, there is no CLIP model weights for that timm combo, it's loading the timm image tower with pretrained imagenet weights, and a random init text tower. If  you want a pretrained CLIP (meaning both image + text tower and projections) you need to use a model config that has a pretrained entry in https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/pretrained.py (or one that is on the huggingface hub)
