### ISSUE TITLE
Is it possible to load only the visual encoder or the text encoder?

### ISSUE THREAD

**Issue by zhangyx1998** [mlfoundations/open_clip#938]
Hi,

As stated in the title, I am attempting to deploy OpenCLIP on an embedded device. In my use case, only one part of CLIP (i.e. text encoder or visual encoder) will be used at a time.

In order to save as much memory as possible, I am looking for a solution that avoids loading unnecessary weights. So far I found only one related post under [OpenAI/CLIP #113](https://github.com/openai/CLIP/issues/113). I am wondering if there exists a better way to achieve this in OpenCLIP.

I would really appreciate any insights on this!

**Comment by rwightman** [comment]
@zhangyx1998 https://github.com/mlfoundations/open_clip/issues/383 

you can do a wee bit of hacking or use the timm variants of the model...

**Comment by zhangyx1998** [comment]
Thanks for the information!
