### ISSUE TITLE
broken jit support

### ISSUE THREAD

**Issue by rom1504** [mlfoundations/open_clip#95]
getting
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults

when trying to load open_clip:ViT-B-32-quickgelu with jit

what could be wrong ?

I figure it's https://github.com/mlfoundations/open_clip/commit/d719ed9c4d79a713907df63b9ca43b48031e12da

@rwightman

**Comment by rwightman** [comment]
@rom1504  woops yeah, I didn't put a jit guard on the checkpointing...

**Comment by rwightman** [comment]
@rom1504 btw, I haven't found scripting the models to be particularly helpful, maybe when nvfuser is ready for primetime. Tracing seems to squeeze a little bit more throughput out.
