### ISSUE TITLE
Does open_clip support add_tokens?

### ISSUE THREAD

**Issue by HyelinNAM** [mlfoundations/open_clip#961]
Hi, Thank you for Great work!

I was wondering if open_clip supports add new tokens?
Currently, I'm working on customization with diffusion model using open_clip.
I saw clip form transformers supports this function, but I wasn't able to find in this package.

Does anyone know how can I add new tokens without hard-coding?

**Comment by rwightman** [comment]
@HyelinNAM the default tokenizer is from the OpenAI CLIP impl which is not very configurable, however tokenizer is created separately from the model, there is a wrapper for HF tokenizers, so you should be able to create the same tokenizer as the transformers CLIP models (for those that are using the OpenAI tokenizer) and use it

**Comment by HyelinNAM** [comment]
I see. Thanks!
