### ISSUE TITLE
SigLIP attention mask

### ISSUE THREAD

**Issue by chs20** [mlfoundations/open_clip#984]
Hi, SigLIP models (e.g. [ViT-B-16-SigLIP](https://github.com/mlfoundations/open_clip/blob/49eac2f27a5bb98a7f7ecc1154918880aa55256c/src/open_clip/model_configs/ViT-B-16-SigLIP.json#L7)) use no causal mask, thereby the attention mask is set to None [here](https://github.com/mlfoundations/open_clip/blob/49eac2f27a5bb98a7f7ecc1154918880aa55256c/src/open_clip/transformer.py#L720).
Does that mean SigLIP attends to padding tokens?

**Comment by rwightman** [comment]
@chs20 there is no explicit masking for the padding tokens yeah, the pad token is the same as eos token for the siglip models though
